"""Generate 01_lab_nlp_text.ipynb for Bab 6."""
import json
from pathlib import Path

OUT = Path("AI-Engineering-Curriculum/06-NLP-Text/01_lab_nlp_text.ipynb")


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


cells = []

# ============================ HEADER ============================
cells.append(md(
    "# 🧪 Lab 6 — Praktikum NLP & Text (dari Nol, Menuju LLM)",
    "",
    "> Pendamping materi Bab 6. Prinsip sama dengan Lab 4 & 5: **semua dibangun dari nol",
    "> dengan numpy** — tokenisasi, skip-gram, RNN, sampling — supaya `Embedding`, `LSTM`,",
    "> dan parameter `temperature` tidak pernah jadi kotak hitam. Teks kita kecil (kamus",
    "> ~20 kata, korpus ~800 karakter) supaya training selesai dalam hitungan detik.",
    "",
    "| Bagian | Topik | Waktu (menit) |",
    "|---|---|---|",
    "| 1 | Tokenisasi & vocabulary: teks → angka | 15 |",
    "| 2 | Padding, OOV, dan kesalahan klasik | 15 |",
    "| 3 | Korpus ko-okurensi: dari mana 'makna' datang | 15 |",
    "| 4 | Skip-gram + negative sampling dari nol | 30 |",
    "| 5 | Klaster semantik: purity + PCA 2D | 20 |",
    "| 6 | Klasifikasi sentimen: embedding vs random | 20 |",
    "| 7 | Char-LM I: bigram count-based & temperature | 20 |",
    "| 8 | Char-LM II: RNN BPTT dari nol vs bigram | 35 |",
    "| 9 | Vanishing gradient: sigmoid vs tanh | 15 |",
    "| 10 | Menuju Transformer & Keras (pemetaan konsep) | 10 |",
    "",
    "Setiap latihan punya cell **✅ Cek** — jalankan, kalau ✅ berarti pemahamanmu benar.",
))

# ============================ BAGIAN 1 ============================
cells.append(md(
    "## Bagian 1 — Tokenisasi & Vocabulary: Teks → Angka",
    "",
    "Model tidak mengerti huruf — hanya angka. Pipeline paling dasar NLP:",
    "",
    "```",
    "teks → token → vocabulary (kata → id) → sequence of ids",
    "```",
    "",
    "Tiga granularitas: **per kata** (vocab besar, tiap kata bermakna), **per karakter**",
    "(vocab kecil, sequence panjang), **subword** (kompromi — dipakai semua LLM modern).",
))

cells.append(code(
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from collections import Counter\n",
    "\n",
    "PAD_ID = 0   # konvensi: 0 = padding, 1 = OOV\n",
    "OOV_ID = 1\n",
    "\n",
    "# Korpus mini bahasa Indonesia\n",
    "KALIMAT = [\n",
    "    \"saya suka nasi goreng\",\n",
    "    \"kucing itu lucu sekali\",\n",
    "    \"mobil baru itu merah\",\n",
    "    \"saya belajar machine learning\",\n",
    "    \"nasi goreng itu enak\",\n",
    "    \"motor baru itu mahal\",\n",
    "]\n",
    "print(f'korpus mini: {len(KALIMAT)} kalimat')\n",
))

cells.append(code(
    "def tokenize_kata(teks):\n",
    "    \"\"\"Teks -> list kata (lowercase, split spasi).\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "def bangun_vocab(kalimat_list):\n",
    "    \"\"\"Return (vocab, w2i, i2w): vocab terurut abjad, w2i = kata->id mulai 0.\"\"\"\n",
    "    # TODO: kumpulkan semua token, sort, buat dua mapping\n",
    "    raise NotImplementedError\n",
    "\n",
    "def encode(kalimat, w2i):\n",
    "    \"\"\"Kalimat (string) -> list id.\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# print(tokenize_kata(\"Saya Suka NASI\"))\n",
    "# vocab, w2i, i2w = bangun_vocab(KALIMAT)\n",
    "# print(len(vocab), vocab[:8])\n",
    "# print(encode(KALIMAT[0], w2i))\n",
))

cells.append(code(
    "# ✅ Cek latihan 1.1\n",
    "assert tokenize_kata(\"Saya Suka NASI\") == ['saya', 'suka', 'nasi']\n",
    "vocab, w2i, i2w = bangun_vocab(KALIMAT)\n",
    "assert vocab == sorted(vocab), 'vocab harus terurut (deterministik!)'\n",
    "assert len(vocab) == len(w2i) == len(i2w)\n",
    "assert all(i2w[w2i[w]] == w for w in vocab), 'roundtrip kata->id->kata harus identitas'\n",
    "ids = encode(KALIMAT[0], w2i)\n",
    "assert ids == [w2i[t] for t in tokenize_kata(KALIMAT[0])]\n",
    "print(f'✅ Latihan 1.1 benar! vocab = {len(vocab)} kata')\n",
    "print('Contoh:', list(zip(KALIMAT[0].split(), encode(KALIMAT[0], w2i))))\n",
))

# ============================ BAGIAN 2 ============================
cells.append(md(
    "## Bagian 2 — Padding, OOV, dan Kesalahan Klasik",
    "",
    "Dua masalah dunia nyata:\n",
    "1. **Panjang beda** → batch butuh persegi → *padding* (isi dengan 0).\n",
    "2. **Kata tak dikenal** → *Out-of-Vocabulary* (OOV) → beri id khusus, JANGAN crash.\n",
    "",
    "⚠️ Kesalahan klasik: membangun vocab dari data TEST (data leakage!) atau membiarkan",
    "OOV menghasilkan error di produksi.",
))

cells.append(code(
    "def pad_sequences(seqs, maxlen):\n",
    "    \"\"\"Semua sequence jadi sama panjang.\n",
    "    - lebih pendek -> isi PAD_ID di BELAKANG (padding='post')\n",
    "    - lebih panjang -> potong dari BELAKANG (truncating='post')\n",
    "    Return array 2D (n, maxlen).\n",
    "    \"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "def encode_aman(kalimat, w2i):\n",
    "    \"\"\"Seperti encode(), tapi kata yang tak ada di vocab -> OOV_ID.\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# seqs = [[5, 2], [3], [7, 1, 4, 6]]\n",
    "# print(pad_sequences(seqs, 3))\n",
    "# print(encode_aman(\"saya makan bakso atom\", w2i))  # 'atom' tak dikenal -> 1\n",
))

cells.append(code(
    "# ✅ Cek latihan 2.1\n",
    "seqs = [[5, 2], [3], [7, 1, 4, 6]]\n",
    "padded = pad_sequences(seqs, 3)\n",
    "assert padded.shape == (3, 3)\n",
    "assert padded.tolist() == [[5, 2, 0], [3, 0, 0], [7, 1, 4]], 'post-padding & post-truncating'\n",
    "assert pad_sequences([], 2).shape == (0, 2)\n",
    "out = encode_aman(\"saya makan bakso atom\", w2i)\n",
    "assert out[-1] == OOV_ID, 'kata tak dikenal harus jadi OOV'\n",
    "assert out[0] == w2i['saya']\n",
    "assert OOV_ID not in encode_aman(KALIMAT[0], w2i), 'kalimat dari korpus bebas OOV'\n",
    "print('✅ Latihan 2.1 benar!')\n",
))

# ============================ BAGIAN 3 ============================
cells.append(md(
    "## Bagian 3 — Korpus Ko-okurensi: Dari Mana \"Makna\" Datang",
    "",
    "Firth (1957): *\"You shall know a word by the company it keeps.\"* Semua word embedding",
    "modern — word2vec, GloVe, sampai embedding LLM — belajar dari **pasangan kata yang",
    "berdekatan**. Kita bangun korpus sintetis dengan struktur yang diketahui, lalu buktikan",
    "embedding menemukan struktur itu **tanpa pernah diberi tahu label**.",
    "",
    "Korpus: kalimat satu-topik (hewan / kendaraan / makanan) + kata sifat positif/negatif",
    "+ kata fungsional. Kita TAHU kategori tiap kata — itu hanya untuk **evaluasi**.",
))

cells.append(code(
    "TOPIK = {\n",
    "    'hewan':     ['kucing', 'anjing', 'burung', 'kelinci'],\n",
    "    'kendaraan': ['mobil', 'motor', 'sepeda', 'kereta'],\n",
    "    'makanan':   ['nasi', 'roti', 'bakso', 'soto'],\n",
    "}\n",
    "POS = ['bagus', 'enak', 'senang', 'mantap']\n",
    "NEG = ['jelek', 'payah', 'kecewa', 'buruk']\n",
    "FUNGSI = ['dan', 'itu', 'di']\n",
    "KAT3 = list(TOPIK)\n",
    "\n",
    "kat_of = {}\n",
    "for k, ws in TOPIK.items():\n",
    "    for w in ws:\n",
    "        kat_of[w] = k\n",
    "for w in POS:\n",
    "    kat_of[w] = 'sifat_pos'\n",
    "for w in NEG:\n",
    "    kat_of[w] = 'sifat_neg'\n",
    "for w in FUNGSI:\n",
    "    kat_of[w] = 'fungsional'\n",
    "\n",
    "def buat_korpus(rng, n=400):\n",
    "    \"\"\"Kalimat sintetis: klausa topik + (70%) klausa sentimen 'itu <sifat>'.\"\"\"\n",
    "    kalimat = []\n",
    "    for _ in range(n):\n",
    "        kat = rng.choice(KAT3)\n",
    "        toks = [str(x) for x in rng.choice(TOPIK[kat], size=int(rng.integers(2, 5)), replace=True)]\n",
    "        for _f in range(int(rng.integers(0, 3))):\n",
    "            toks.insert(int(rng.integers(0, len(toks) + 1)), str(rng.choice(FUNGSI)))\n",
    "        if rng.random() < 0.70:\n",
    "            pool = POS if rng.random() < 0.5 else NEG\n",
    "            toks.append('itu')\n",
    "            for _s in range(int(rng.integers(1, 3))):\n",
    "                toks.append(str(rng.choice(pool)))\n",
    "            if rng.random() < 0.3:\n",
    "                toks.append(str(rng.choice(pool)))\n",
    "        kalimat.append(toks)\n",
    "    return kalimat\n",
    "\n",
    "rng_korpus = np.random.default_rng(42)\n",
    "korpus = buat_korpus(rng_korpus)\n",
    "print('contoh:', [' '.join(s) for s in korpus[:3]])\n",
    "cnt = Counter(w for s in korpus for w in s)\n",
    "print('20 kata terpopuler:', cnt.most_common(8))\n",
))

cells.append(code(
    "def pasangan_skipgram(kalimat_list, w2i, window=2):\n",
    "    \"\"\"Semua pasangan (target, konteks) dalam jendela `window` dua arah.\n",
    "    Kalimat [a, b, c] window 1 -> (a,b), (b,a), (b,c), (c,b).\n",
    "    \"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# _w2i = {'a': 0, 'b': 1, 'c': 2}\n",
    "# print(pasangan_skipgram([['a', 'b', 'c']], _w2i, window=1))\n",
))

cells.append(code(
    "# ✅ Cek latihan 3.1\n",
    "_w2i = {'a': 0, 'b': 1, 'c': 2}\n",
    "got = sorted(pasangan_skipgram([['a', 'b', 'c']], _w2i, window=1))\n",
    "assert got == [(0, 1), (1, 0), (1, 2), (2, 1)], f'dua arah, tanpa diri-sendiri: {got}'\n",
    "vocab6, w2i6, i2w6 = bangun_vocab([' '.join(s) for s in korpus])\n",
    "pairs6 = pasangan_skipgram(korpus, w2i6, window=2)\n",
    "assert len(pairs6) > 4000, f'korpus harus menghasilkan ribuan pasangan: {len(pairs6)}'\n",
    "# statistik: pasangan satu-kategori harus dominan\n",
    "same = sum(1 for t, c in pairs6 if kat_of[i2w6[t]] == kat_of[i2w6[c]])\n",
    "print(f'✅ Latihan 3.1 benar! {len(pairs6)} pasangan, {same / len(pairs6):.0%} satu kategori')\n",
))

# ============================ BAGIAN 4 ============================
cells.append(md(
    "## Bagian 4 — Skip-gram + Negative Sampling dari Nol",
    "",
    "Ide: untuk tiap pasangan (target, konteks), buat vektor target & konteks **menarik",
    "saling mendekat**, sementara `k` kata acak (negative samples) **didorong menjauh**.",
    "Tak ada label makna — murni statistik ko-okurensi. Makna muncul sebagai efek samping.",
    "",
    "```",
    "loss  = −log σ(v_t · u_c)  +  Σ_neg −log σ(−v_t · u_neg)",
    "grad  = (σ(z) − y) · u     dengan y=1 utk pasangan asli, y=0 utk noise",
    "```",
))

cells.append(code(
    "# Persiapan: aktivasi, ukuran kemiripan, dan distribusi unigram untuk noise\n",
    "def sigmoid(z):\n",
    "    return 1.0 / (1.0 + np.exp(-np.clip(z, -30, 30)))\n",
    "\n",
    "def cos_sim(a, b):\n",
    "    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))\n",
    "\n",
    "freq_uni = np.array([cnt[w] for w in vocab6], dtype=float)\n",
    "freq_uni = freq_uni / freq_uni.sum()\n",
    "freq_uni[-1] = 1.0 - freq_uni[:-1].sum()   # paksa jumlah = 1 (presisi float)\n",
    "print(f'persiapan selesai: {len(pairs6)} pasangan, vocab {len(vocab6)}')\n",
))

cells.append(code(
    "def train_skipgram(pairs, vocab_size, freq_unigram,\n",
    "                   dim=16, epochs=5, lr=0.05, k_neg=3, seed=0):\n",
    "    \"\"\"Skip-gram + negative sampling.\n",
    "    pairs        : list (target_id, context_id)\n",
    "    freq_unigram : array (vocab_size,) probabilitas unigram (untuk sampling noise)\n",
    "    Return (W_in, loss_history): W_in (vocab_size, dim) = embedding matrix.\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "    W_in = rng.normal(0, 0.1, (vocab_size, dim))\n",
    "    W_out = rng.normal(0, 0.1, (vocab_size, dim))\n",
    "    noise = np.asarray(freq_unigram, dtype=float) ** 0.75   # trik word2vec: ^0.75\n",
    "    noise = noise / noise.sum()\n",
    "    loss_hist = []\n",
    "    for ep in range(epochs):\n",
    "        lr_ep = lr * (1.0 - 0.5 * ep / epochs)              # lr decay linear\n",
    "        tot, cnt = 0.0, 0\n",
    "        for (t, c) in pairs:\n",
    "            # TODO 1: pasangan asli — hitung s = sigmoid(W_in[t] @ W_out[c]),\n",
    "            #         grad_v = (s - 1) * W_out[c], grad_u = (s - 1) * W_in[t]\n",
    "            # TODO 2: k_neg sampel noise dari `noise` — update W_out[neg] langsung,\n",
    "            #         tambahkan sn * W_out[neg] ke grad_v\n",
    "            # TODO 3: W_in[t] -= lr_ep * grad_v ; W_out[c] -= lr_ep * grad_u\n",
    "            #         akumulasi loss: -log(s) + Σ -log(1 - sn)\n",
    "            raise NotImplementedError\n",
    "        loss_hist.append(tot / cnt)\n",
    "    return W_in, loss_hist\n",
))

cells.append(code(
    "# ✅ Cek latihan 4.1 — gradient check analitik vs numerik\n",
    "def _gc_step(W_in, W_out, t, c, negs, lr):\n",
    "    \"\"\"Satu langkah train_skipgram; return (loss, salinan W_in, W_out).\"\"\"\n",
    "    v, u = W_in[t], W_out[c]\n",
    "    s = sigmoid(float(v @ u))\n",
    "    gv = (s - 1.0) * u\n",
    "    gu = (s - 1.0) * v\n",
    "    L = -np.log(max(s, 1e-12))\n",
    "    W_out = W_out.copy()\n",
    "    for n_id in negs:\n",
    "        if n_id == c:\n",
    "            continue\n",
    "        un = W_out[n_id]\n",
    "        sn = sigmoid(float(v @ un))\n",
    "        gv += sn * un\n",
    "        W_out[n_id] -= lr * (sn * v)\n",
    "        L += -np.log(max(1 - sn, 1e-12))\n",
    "    W_in2 = W_in.copy()\n",
    "    W_in2[t] -= lr * gv\n",
    "    W_out[c] -= lr * gu\n",
    "    return L, W_in2, W_out\n",
    "\n",
    "Vx, Dx = 6, 8\n",
    "rng = np.random.default_rng(9)\n",
    "Win0 = rng.normal(0, 0.5, (Vx, Dx))\n",
    "Wout0 = rng.normal(0, 0.5, (Vx, Dx))\n",
    "prob_x = np.full(Vx, 1 / Vx)\n",
    "# loss total sebelum vs sesudah 1 langkah harus MENURUN (langkah gradient descent)\n",
    "def loss_total(Wi, Wo, t, c, negs):\n",
    "    L, _, _ = _gc_step(Wi, Wo, t, c, negs, 0.0)\n",
    "    return L\n",
    "# verifikasi manual: gradien analitik gradien-check pada v_t\n",
    "eps = 1e-6\n",
    "t0, c0, negs0 = 2, 4, [0, 3, 5]\n",
    "def f_loss():\n",
    "    s = sigmoid(float(Win0[t0] @ Wout0[c0]))\n",
    "    L = -np.log(max(s, 1e-12))\n",
    "    for n_id in negs0:\n",
    "        if n_id == c0:\n",
    "            continue\n",
    "        sn = sigmoid(float(Win0[t0] @ Wout0[n_id]))\n",
    "        L += -np.log(max(1 - sn, 1e-12))\n",
    "    return L\n",
    "Win0[t0, 0] += eps; Lp = f_loss()\n",
    "Win0[t0, 0] -= 2 * eps; Lm = f_loss()\n",
    "Win0[t0, 0] += eps\n",
    "g_num = (Lp - Lm) / (2 * eps)\n",
    "# analitik: dL/dv = (s_c - 1) u_c + Σ (s_n) u_n\n",
    "v_ = Win0[t0]\n",
    "g_an = (sigmoid(float(v_ @ Wout0[c0])) - 1.0) * Wout0[c0]\n",
    "for n_id in negs0:\n",
    "    if n_id == c0:\n",
    "        continue\n",
    "    g_an += sigmoid(float(v_ @ Wout0[n_id])) * Wout0[n_id]\n",
    "assert abs(g_an[0] - g_num) < 1e-5, f'gradien meleset: analitik {g_an[0]} vs numerik {g_num}'\n",
    "print('✅ Latihan 4.1 benar! Gradien skip-gram terverifikasi numerik.')\n",
))

cells.append(code(
    "# Jalankan training penuh & lihat loss turun\n",
    "E, sg_loss = train_skipgram(pairs6, len(vocab6), freq_uni, seed=0)\n",
    "assert len(sg_loss) == 5 and sg_loss[-1] < sg_loss[0], 'loss harus turun'\n",
    "plt.plot(sg_loss, marker='o')\n",
    "plt.xlabel('epoch'); plt.ylabel('loss rata-rata per pasangan')\n",
    "plt.title('Skip-gram: loss turun = pasangan asli makin dekat, noise makin jauh')\n",
    "plt.show()\n",
    "print(f'✅ loss: {sg_loss[0]:.3f} -> {sg_loss[-1]:.3f}')\n",
))

# ============================ BAGIAN 5 ============================
cells.append(md(
    "## Bagian 5 — Klaster Semantik: Purity + PCA 2D",
    "",
    "Sekarang bukti kuncinya: kata-kata satu kategori harus jadi **tetangga terdekat**",
    "(ukuran *purity*), dan proyeksi PCA 2D harus memperlihatkan 3 gugus — tanpa kita",
    "pernah memberi tahu model soal kategori.",
))

cells.append(code(
    "CATS = set(KAT3)   # kategori yang diuji klaster-nya\n",
    "print('kategori diuji:', CATS)\n",
))

cells.append(code(
    "def nn_purity(E, vocab, kat_map, kategori_set):\n", 
    "    \"\"\"Proporsi kata (dalam kategori_set) yang tetangga terdekatnya (cosine)\n",
    "    berasal dari kategori yang sama. Ini tes 'makna muncul sendiri'.\"\"\"\n",
    "    # TODO: loop kata dalam kategori_set, cari NN via cos_sim, bandingkan kategori\n",
    "    raise NotImplementedError\n",
    "\n",
    "def pca_2d(X):\n",
    "    \"\"\"PCA manual ke 2 dimensi: center -> cov -> eigenvector teratas.\n",
    "    Return (n, 2).\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# print(nn_purity(E, vocab6, kat_of, CATS))\n",
    "# print(pca_2d(np.random.default_rng(0).normal(size=(5, 4))).shape)\n",
))

cells.append(code(
    "# ✅ Cek latihan 5.1\n",
    "# pca: proyeksi data 2D harus mempertahankan variance terbesar\n",
    "rng = np.random.default_rng(1)\n",
    "X_tes = rng.normal(size=(50, 5))\n",
    "X_tes[:, 0] *= 10.0                      # dimensi pertama dominan\n",
    "P_tes = pca_2d(X_tes)\n",
    "assert P_tes.shape == (50, 2)\n",
    "var_axis = P_tes.var(0)\n",
    "assert var_axis[0] >= var_axis[1], 'sumbu pertama harus variance terbesar'\n",
    "# proyeksi ke sumbu dominan harus ~ kolom pertama (yang distandarkan)\n",
    "korel = abs(np.corrcoef(P_tes[:, 0], X_tes[:, 0])[0, 1])\n",
    "assert korel > 0.99, f'PC1 harus sejajar dimensi dominan: {korel}'\n",
    "print('✅ PCA manual benar!')\n",
))

cells.append(code(
    "purity = nn_purity(E, vocab6, kat_of, CATS)\n",
    "print(f'NN purity: {purity:.2f}  (1.00 = setiap kata konten punya tetangga satu kategori)')\n",
    "assert purity >= 0.9, f'embedding harus mengelompok per kategori: {purity}'\n",
    "\n",
    "P2 = pca_2d(E)\n",
    "colors = {'hewan': 'tab:red', 'kendaraan': 'tab:blue', 'makanan': 'tab:green',\n",
    "          'sifat_pos': 'tab:orange', 'sifat_neg': 'tab:purple', 'fungsional': 'gray'}\n",
    "plt.figure(figsize=(9, 7))\n",
    "for i, w in enumerate(vocab6):\n",
    "    plt.scatter(P2[i, 0], P2[i, 1], c=colors[kat_of[w]], s=110)\n",
    "    plt.annotate(w, (P2[i, 0], P2[i, 1]), xytext=(4, 4), textcoords='offset points', fontsize=10)\n",
    "plt.title('Embedding skip-gram diproyeksi PCA 2D\\n(3 gugus topik + kutub sentimen) — tanpa label saat training!')\n",
    "plt.grid(alpha=0.3)\n",
    "plt.show()\n",
    "print('✅ Klaster semantik TERBUKTI muncul dari ko-okurensi semata.')\n",
))

# ============================ BAGIAN 6 ============================
cells.append(md(
    "## Bagian 6 — Klasifikasi Sentimen: Embedding vs Random",
    "",
    "Pertanyaan praktis: apakah embedding \"dari nol\" ini benar-benar berguna? Uji dengan",
    "klasifikasi sentimen kalimat: fitur = **rata-rata embedding kata** (cara paling polos),",
    "klasifikasi = regresi logistik (dari Bab 3!). Bandingkan tiga fitur:\n",
    "1. **One-hot mean** — tiap kata = vektor identitas (tak ada makna, hanya identitas).\n",
    "2. **Random embedding** — vektor acak tetap per kata.\n",
    "3. **Skip-gram embedding** — hasil Bagian 4.\n",
))

cells.append(code(
    "def fitur_avg(kalimat_toks, E, w2i_):\n",
    "    \"\"\"Rata-rata vektor embedding kata-kata kalimat. Return vektor (dim,).\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "def fitur_onehot_mean(kalimat_toks, w2i_):\n",
    "    \"\"\"Rata-rata one-hot: vektor (vocab,) dengan 1/n_jumlah_kata di posisi tiap kata.\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "def label_sentimen(toks):\n",
    "    \"\"\"+1 jika kata POS dominan, -1 jika NEG dominan, 0 kalau tidak ada sifat.\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# print(label_sentimen(['saya', 'suka', 'bagus']))\n",
))

cells.append(code(
    "# ✅ Cek latihan 6.1\n",
    "assert label_sentimen(['kucing', 'bagus']) == 1\n",
    "assert label_sentimen(['kucing', 'jelek', 'payah']) == -1\n",
    "assert label_sentimen(['kucing', 'bagus', 'jelek']) == 0, 'seri -> 0'\n",
    "assert label_sentimen(['kucing', 'mobil']) == 0, 'tanpa sifat -> 0'\n",
    "f1 = fitur_avg(['kucing', 'bagus'], E, w2i6)\n",
    "assert f1.shape == (E.shape[1],)\n",
    "assert np.allclose(f1, (E[w2i6['kucing']] + E[w2i6['bagus']]) / 2)\n",
    "f2 = fitur_onehot_mean(['a', 'b', 'a'], {'a': 0, 'b': 1})\n",
    "assert f2.shape == (2,) and np.allclose(f2, [2 / 3, 1 / 3]), 'one-hot mean terhitung benar'\n",
    "print('✅ Latihan 6.1 benar!')\n",
))

cells.append(code(
    "def sigmoid_bin(z):\n",
    "    return 1.0 / (1.0 + np.exp(-np.clip(z, -30, 30)))\n",
    "\n",
    "def latih_logreg(X, y, epochs=300, lr=0.5, seed=0):\n",
    "    \"\"\"Regresi logistik batch GD (Bab 3) untuk label biner. Return (w, b).\"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "    idx = rng.permutation(len(X))\n",
    "    n_tr = int(0.75 * len(X))\n",
    "    Xtr, ytr = X[idx[:n_tr]], y[idx[:n_tr]]\n",
    "    Xva, yva = X[idx[n_tr:]], y[idx[n_tr:]]\n",
    "    w = np.zeros(X.shape[1]); b = 0.0\n",
    "    for ep in range(epochs):\n",
    "        p = sigmoid_bin(Xtr @ w + b)\n",
    "        w -= lr * (Xtr.T @ (p - ytr) / len(ytr))\n",
    "        b -= lr * (p - ytr).mean()\n",
    "    pv = sigmoid_bin(Xva @ w + b)\n",
    "    ce = float(-np.mean(yva * np.log(pv + 1e-12) + (1 - yva) * np.log(1 - pv + 1e-12)))\n",
    "    acc = float(((pv >= 0.5) == yva).mean())\n",
    "    return acc, ce\n",
    "\n",
    "# Dataset: hanya kalimat bersifat (ada kata sifat), label dari sisi dominan\n",
    "data_sent = [(s, label_sentimen(s)) for s in korpus if label_sentimen(s) != 0]\n",
    "X_oh = np.array([fitur_onehot_mean(s, w2i6) for s, _ in data_sent])\n",
    "X_rd = np.array([fitur_avg(s, np.random.default_rng(7).normal(0, 0.1, (len(vocab6), E.shape[1])), w2i6) for s, _ in data_sent])\n",
    "X_sg = np.array([fitur_avg(s, E, w2i6) for s, _ in data_sent])\n",
    "y_bin = np.array([1.0 if l == 1 else 0.0 for _, l in data_sent])\n",
    "\n",
    "acc_oh, ce_oh = latih_logreg(X_oh, y_bin)\n",
    "acc_rd, ce_rd = latih_logreg(X_rd, y_bin)\n",
    "acc_sg, ce_sg = latih_logreg(X_sg, y_bin)\n",
    "print(f'one-hot mean : acc {acc_oh:.3f}  (CE {ce_oh:.3f})')\n",
    "print(f'random emb   : acc {acc_rd:.3f}  (CE {ce_rd:.3f})')\n",
    "print(f'skip-gram emb: acc {acc_sg:.3f}  (CE {ce_sg:.3f})')\n",
    "assert acc_sg > 0.9, f'skip-gram harus mencapai >= 0.9: {acc_sg}'\n",
    "assert ce_sg < 0.35, f'cross-entropy skip-gram harus rendah: {ce_sg}'\n",
    "print('✅ Embedding skip-gram memberi fitur yang JAUH lebih informatif.')\n",
))

cells.append(md(
    "**Pertanyaan pemahaman (jawab dengan kata-kata di cell markdown):**",
    "",
    "1. Kenapa one-hot mean hanya bisa menghafal kata mana yang positif — dan kalah jauh",
    "   di cross-entropy? (hint: ada info apa di embedding yang TIDAK ada di one-hot?)",
    "2. Kalau korpus diubah jadi 6 topik + 10 kategori sifat, mana yang lebih mahal:",
    "   menambah baris one-hot atau menambah dimensi embedding? Kenapa embedding lebih",
    "   tahan terhadap vocab besar?",
    "3. Ini persis alasan Bab 12 (RAG) memakai embedding dokumen. Apa yang \"dicari\"",
    "   cosine similarity di RAG, berdasarkan eksperimenmu di Bagian 5?",
))

# ============================ BAGIAN 7 ============================
cells.append(md(
    "## Bagian 7 — Char-LM I: Bigram Count-Based & Temperature",
    "",
    "Model bahasa = model distribusi token berikutnya. Versi paling sederhana: **bigram**",
    "`P(ch | ch_sebelumnya)` dihitung dengan menghitung frekuensi (dengan smoothing).",
    "Lalu kita generate dengan **temperature**: mengubah `p → p^(1/T)` sebelum dinormalisasi.",
    "",
    "- `T → 0`: deterministik (argmax)",
    "- `T = 1`: sesuai distribusi asli",
    "- `T > 1`: lebih acak / kreatif",
))

cells.append(code(
    "KALIMAT_LM = [\n",
    "    'adi makan nasi', 'budi minum air', 'citra membaca buku',\n",
    "    'dewi menulis surat', 'eka bermain bola', 'fajar melihat kaca',\n",
    "    'gita menyanyi lagu', 'hadi membuka kelas', 'indah menanam bunga',\n",
    "    'joko menghitung uang', 'kartika menjahit baju', 'lina menjual buah',\n",
    "    'maya menyapu lantai', 'nanda mendengar kabar', 'okta membeli roti',\n",
    "    'putri menyiram tanaman', 'rizky mengejar bus', 'sari mencuci piring',\n",
    "    'tono memperbaiki motor', 'utami mengaduk adonan', 'vina mengambil paket',\n",
    "    'wawan mengangkat meja', 'yuni menjahit kerudung', 'zahra mengeringkan baju',\n",
    "    'bagus membawa kasur', 'candra mengisi gelas', 'dian menyusun kartu',\n",
    "    'fitri menata piring', 'gilang menyalakan lampu', 'husni menutup pintu',\n",
    "    'irma menggulai sayur', 'krisna meniup terompet',\n",
    "    'makan nasi itu enak', 'minum air itu menyegarkan',\n",
    "    'membaca buku itu bagus', 'menulis surat itu mudah',\n",
    "    'bermain bola itu seru', 'melihat kaca itu aneh',\n",
    "    'menyanyi lagu itu indah', 'membuka kelas itu pagi',\n",
    "    'adi minum teh', 'budi makan roti', 'citra menjahit baju',\n",
    "    'dewi menyiram bunga', 'eka membaca koran', 'fajar mengejar kucing',\n",
    "    'gita membeli buku', 'hadi menyapu halaman', 'indah menjahit gaun',\n",
    "    'joko menanam padi', 'kartika menyusun bunga', 'lina menghitung uang',\n",
    "    'maya membuka pintu', 'nanda memperbaiki sepeda', 'okta mengambil air',\n",
    "    'putri menulis surat', 'rizky menyiram tanaman', 'sari mengupas kentang',\n",
    "    'tono membawa tas', 'utami meniup peluit', 'vina menjahit sarung',\n",
    "    'wawan mengaduk kopi', 'yuni menata meja', 'zahra mengeringkan rambut',\n",
    "    'makan roti itu enak', 'minum teh itu nikmat', 'membaca koran itu bagus',\n",
    "    'menulis surat itu mudah', 'bermain bola itu seru', 'melihat kaca itu aneh',\n",
    "]\n",
    "teks_lm = '\\n'.join(KALIMAT_LM) + '\\n'\n",
    "chars_lm = sorted(set(teks_lm))\n",
    "c2i_lm = {c: i for i, c in enumerate(chars_lm)}\n",
    "i2c_lm = {i: c for c, i in c2i_lm.items()}\n",
    "C_lm = len(chars_lm)\n",
    "seq_lm = [c2i_lm[c] for c in teks_lm]\n",
    "print(f'korpus {len(teks_lm)} karakter, vocab char = {C_lm}')\n",
))

cells.append(code(
    "def bigram_matrix(seq, vocab_size, alpha=0.5):\n",
    "    \"\"\"Matriks hitungan bigram + smoothing alpha. Return P (baris = distribusi next-char).\"\"\"\n",
    "    # TODO: counts[i, j] = 1 + alpha ( smoothing) untuk semua i,j,\n",
    "    #       lalu counts[a, b] += 1 untuk tiap transisi a->b; normalisasi per baris\n",
    "    raise NotImplementedError\n",
    "\n",
    "def ee_bigram(seq, P):\n",
    "    \"\"\"Cross-entropy rata-rata (nats/char): -mean log P[next | prev].\"\"\"\n",
    "    # TODO\n",
    "    raise NotImplementedError\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# P = bigram_matrix([0, 1, 0, 2], 3, alpha=0.5)\n",
    "# print(np.round(P, 3))  # tiap baris jumlah = 1\n",
))

cells.append(code(
    "# ✅ Cek latihan 7.1\n",
    "P_t = bigram_matrix([0, 1, 0, 2], 3, alpha=0.5)\n",
    "assert P_t.shape == (3, 3)\n",
    "assert np.allclose(P_t.sum(axis=1), 1.0), 'tiap baris = distribusi'\n",
    "# transisi 0->1 muncul 1x; baris 0: 0->0 (0 kali), 0->1 (1), 0->2 (0)\n",
    "# transisi 0->1 muncul 1x; baris 0: 0->0 (1x via 0->1->0), 0->1 (1x), 0->2 (1x)\n",
    "# counts baris 0 = [1.5, 2.5, 2.5] -> P[0,1] = 2.5/6.5\n",
    "assert abs(P_t[0, 1] - 2.5 / 6.5) < 1e-9, 'baris 0: counts [1.5, 2.5, 2.5] (0->1 dan 0->2 masing +1)'\n",
    "ee_u = -np.mean(np.log(np.bincount(seq_lm, minlength=C_lm)[seq_lm[1:]] / len(seq_lm)))\n",
    "P_lm = bigram_matrix(seq_lm, C_lm)\n",
    "ee_b = ee_bigram(seq_lm, P_lm)\n",
    "print(f'EE unigram {ee_u:.3f} vs bigram {ee_b:.3f} nats/char')\n",
    "assert ee_b < ee_u - 0.2, 'bigram harus jauh lebih baik dari unigram'\n",
    "print('✅ Latihan 7.1 benar! Bigram menang telak (konteks 1 char sudah sangat membantu).')\n",
))

cells.append(code(
    "def sample_bigram(P, seed_str, n_char, temp, rng):\n",
    "    \"\"\"Generate n_char karakter dengan temperature sampling.\"\"\"\n",
    "    out = seed_str\n",
    "    cur = c2i_lm[seed_str[-1]]\n",
    "    for _ in range(n_char):\n",
    "        # TODO: p = P[cur] ** (1/temp) -> normalisasi -> sampling -> append\n",
    "        raise NotImplementedError\n",
    "    return out\n",
    "\n",
    "# --- uji sendiri ---\n",
    "# rng_g = np.random.default_rng(1)\n",
    "# for t in (0.3, 1.0, 1.8):\n",
    "#     print(f'--- T={t} ---')\n",
    "#     print(sample_bigram(P_lm, 'm', 100, t, rng_g))\n",
))

cells.append(code(
    "# ✅ Cek latihan 7.2 — perilaku temperature\n",
    "rng_g = np.random.default_rng(1)\n",
    "T_kecil = np.array([sample_bigram(P_lm, 'm', 80, 0.3, rng_g) for _ in range(20)])\n",
    "T_besar = np.array([sample_bigram(P_lm, 'm', 80, 1.8, rng_g) for _ in range(20)])\n",
    "def entropy_char(teks_list):\n",
    "    cnts = Counter(''.join(teks_list))\n",
    "    tot = sum(cnts.values())\n",
    "    return float(-sum(v / tot * np.log(v / tot) for v in cnts.values()))\n",
    "h_kecil, h_besar = entropy_char(T_kecil), entropy_char(T_besar)\n",
    "print(f'entropy karakter: T=0.3 -> {h_kecil:.3f} | T=1.8 -> {h_besar:.3f}')\n",
    "assert h_besar > h_kecil, 'T tinggi harus menghasilkan teks lebih beragam'\n",
    "# T=0.3 harus sangat repetitif (karakter unik sedikit per sampel)\n",
    "unik_kecil = np.mean([len(set(t)) for t in T_kecil])\n",
    "unik_besar = np.mean([len(set(t)) for t in T_besar])\n",
    "assert unik_besar > unik_kecil\n",
    "print('✅ Latihan 7.2 benar! T rendah = repetitif & aman; T tinggi = beragam & liar.')\n",
    "print('\\n--- contoh T=0.3 ---\\n' + sample_bigram(P_lm, 'm', 90, 0.3, np.random.default_rng(3)))\n",
    "print('\\n--- contoh T=1.8 ---\\n' + sample_bigram(P_lm, 'm', 90, 1.8, np.random.default_rng(3)))\n",
))

# ============================ BAGIAN 8 ============================
cells.append(md(
    "## Bagian 8 — Char-LM II: RNN dari Nol (BPTT) vs Bigram",
    "",
    "Bigram hanya melihat **1 karakter ke belakang**. RNN membawa *hidden state* yang",
    "diringkat dari **seluruh konteks**. Kita bangun RNN Elman penuh: forward, **BPTT**",
    "(backpropagation through time), sampling — lalu buktikan dia mengalahkan bigram.",
    "",
    "```",
    "h_t = tanh(W_x·x_t + W_h·h_{t-1} + b_h)     (forward)",
    "dWh += da_t · h_{t-1}ᵀ                       (backward, akumulasi sepanjang waktu)",
    "dh_{t-1} = W_hᵀ · da_t                       (gradien mengalir ke belakang)",
    "```",
    "Konteks CTX=4 karakter — cukup untuk menangkap awalan kata ('men', 'mem', 'ber').",
))

cells.append(code(
    "CTX = 4\n",
    "X_rnn, y_rnn = [], []\n",
    "for i in range(len(seq_lm) - CTX):\n",
    "    X_rnn.append(seq_lm[i:i + CTX])\n",
    "    y_rnn.append(seq_lm[i + CTX])\n",
    "X_rnn, y_rnn = np.array(X_rnn), np.array(y_rnn)\n",
    "perm = np.random.default_rng(0).permutation(len(X_rnn))\n",
    "X_rnn, y_rnn = X_rnn[perm], y_rnn[perm]        # SHUFFLE dulu -> split valid adil\n",
    "n_tr = int(0.75 * len(X_rnn))\n",
    "Xtr, ytr, Xva, yva = X_rnn[:n_tr], y_rnn[:n_tr], X_rnn[n_tr:], y_rnn[n_tr:]\n",
    "print(f'train {len(Xtr)}, val {len(Xva)}')\n",
    "\n",
    "def onehot_batch(ids, width):\n",
    "    z = np.zeros((len(ids), width))\n",
    "    z[np.arange(len(ids)), ids] = 1.0\n",
    "    return z\n",
))

cells.append(code(
    "def rnn_forward(X, params, ctx):\n",
    "    \"\"\"Forward RNN. X: (n, ctx). Return (probs, cache).\n",
    "    cache = (hs, Hs): daftar hidden state & pre-aktivasi per langkah waktu.\n",
    "    \"\"\"\n",
    "    Wx, Wh, Wy, bh, by = params\n",
    "    n = len(X)\n",
    "    hidden = Wh.shape[0]\n",
    "    hs = [np.zeros((n, hidden))]\n",
    "    Hs = []                      # pre-activation (untuk backward tanh)\n",
    "    # TODO: loop t dalam range(ctx):\n",
    "    #   h_pre = hs[t] @ Wh.T + onehot_batch(X[:, t], C_lm) @ Wx + bh\n",
    "    #   hs.append(tanh(h_pre)); Hs.append(h_pre)\n",
    "    # lalu: logits = hs[-1] @ Wy + by -> softmax stabil -> return (probs, (hs, Hs))\n",
    "    raise NotImplementedError\n",
    "\n",
    "def rnn_backward(probs, y, X, params, cache, ctx):\n",
    "    \"\"\"BPTT: return (dWx, dWh, dWy, dbh, dby).\"\"\"\n",
    "    Wx, Wh, Wy, bh, by = params\n",
    "    hs, Hs = cache\n",
    "    n = len(X)\n",
    "    dWx = np.zeros_like(Wx); dWh = np.zeros_like(Wh)\n",
    "    dbh = np.zeros_like(bh)\n",
    "    # TODO 1: softmax cross-entropy -> dlogits = (probs - onehot(y)) / n\n",
    "    # TODO 2: dWy = hs[-1].T @ dlogits ; dby = dlogits.sum(0); dh = dlogits @ Wy.T\n",
    "    # TODO 3: loop t mundur: da = dh * (1 - tanh(Hs[t])**2)\n",
    "    #         dWx += onehot_batch(X[:, t], C_lm).T @ da ; dWh += da.T @ hs[t]\n",
    "    #         dbh += da.sum(0) ; dh = da @ Wh   <- gradien mengalir ke waktu!\n",
    "    raise NotImplementedError\n",
))

cells.append(code(
    "def latih_rnn(hidden=32, epochs=150, lr=0.2, batch=32, seed=0, ctx=CTX):\n",
    "    rng = np.random.default_rng(seed)\n",
    "    Wx = rng.normal(0, 0.5, (C_lm, hidden))\n",
    "    Wh = rng.normal(0, 0.5, (hidden, hidden))\n",
    "    Wy = rng.normal(0, 0.1, (hidden, C_lm))\n",
    "    bh = np.zeros(hidden); by = np.zeros(C_lm)\n",
    "    params = [Wx, Wh, Wy, bh, by]\n",
    "    first, last = None, None\n",
    "    for ep in range(epochs):\n",
    "        order = rng.permutation(len(Xtr))\n",
    "        tot, cnt = 0.0, 0\n",
    "        for s in range(0, len(order), batch):\n",
    "            bidx = order[s:s + batch]\n",
    "            Xb, yb = Xtr[bidx], ytr[bidx]\n",
    "            probs, cache = rnn_forward(Xb, params, ctx)\n",
    "            n = len(bidx)\n",
    "            tot += -np.mean(np.log(probs[np.arange(n), yb] + 1e-12)); cnt += 1\n",
    "            grads = rnn_backward(probs, yb, Xb, params, cache, ctx)\n",
    "            dWx, dWh, dWy, dbh, dby = grads\n",
    "            for g in grads:\n",
    "                np.clip(g, -5, 5, out=g)     # gradient clipping\n",
    "            Wx -= lr * dWx; Wh -= lr * dWh; Wy -= lr * dWy\n",
    "            bh -= lr * dbh; by -= lr * dby\n",
    "        if ep == 0:\n",
    "            first = tot / cnt\n",
    "        last = tot / cnt\n",
    "    # akurasi val\n",
    "    probs, _ = rnn_forward(Xva, params, ctx)\n",
    "    acc = float((probs.argmax(1) == yva).mean())\n",
    "    ce = float(-np.mean(np.log(probs[np.arange(len(yva)), yva] + 1e-12)))\n",
    "    return dict(params=params, first=first, last=last, acc=acc, ce=ce,\n",
    "                hidden=hidden, rng=rng)\n",
    "\n",
    "model_rnn = latih_rnn()\n",
    "print(f'loss {model_rnn[\"first\"]:.3f} -> {model_rnn[\"last\"]:.3f} | val acc {model_rnn[\"acc\"]:.3f} | CE {model_rnn[\"ce\"]:.3f}')\n",
    "\n",
    "# baseline bigram pada split yang sama\n",
    "counts_b = np.ones((C_lm, C_lm))\n",
    "for a, b in zip(seq_lm[:n_tr + CTX], seq_lm[1:n_tr + CTX]):\n",
    "    counts_b[a, b] += 1\n",
    "P_tr = counts_b / counts_b.sum(1, keepdims=True)\n",
    "ce_b = float(-np.mean(np.log(P_tr[Xva[:, -1], yva] + 1e-12)))\n",
    "acc_b = float((np.array([P_tr[x[-1]].argmax() for x in Xva]) == yva).mean())\n",
    "print(f'bigram: val acc {acc_b:.3f} | CE {ce_b:.3f}')\n",
    "\n",
    "assert model_rnn['last'] < model_rnn['first'], 'loss training harus turun'\n",
    "assert model_rnn['acc'] > acc_b + 0.05, \\\n",
    "    f'RNN harus mengalahkan bigram: {model_rnn[\"acc\"]:.3f} vs {acc_b:.3f}'\n",
    "print('✅ RNN (konteks penuh via hidden state) mengalahkan bigram (1 char).')\n",
))

cells.append(code(
    "# ✅ Cek latihan 8.1 — gradient check BPTT pada batch kecil\n",
    "def _grad_check_rnn():\n",
    "    rng = np.random.default_rng(11)\n",
    "    hidden = 8\n",
    "    params = [rng.normal(0, 0.4, (C_lm, hidden)), rng.normal(0, 0.4, (hidden, hidden)),\n",
    "              rng.normal(0, 0.1, (hidden, C_lm)), np.zeros(hidden), np.zeros(C_lm)]\n",
    "    Xb, yb = Xtr[:4], ytr[:4]\n",
    "    probs, cache = rnn_forward(Xb, params, CTX)\n",
    "    grads = rnn_backward(probs, yb, Xb, params, cache, CTX)\n",
    "    def loss_fn(p):\n",
    "        pr, _ = rnn_forward(Xb, p, CTX)\n",
    "        return float(-np.mean(np.log(pr[np.arange(4), yb] + 1e-12)))\n",
    "    eps = 1e-6\n",
    "    nama = ['dWx', 'dWh', 'dWy', 'dbh', 'dby']\n",
    "    for pi in range(5):\n",
    "        P_ = params[pi]\n",
    "        G_ = grads[pi]\n",
    "        it = np.nditer(P_, flags=['multi_index'])\n",
    "        cek = 0\n",
    "        while not it.finished:\n",
    "            idx = it.multi_index\n",
    "            orig = P_[idx]\n",
    "            P_[idx] = orig + eps; Lp = loss_fn(params)\n",
    "            P_[idx] = orig - eps; Lm = loss_fn(params)\n",
    "            P_[idx] = orig\n",
    "            g_num = (Lp - Lm) / (2 * eps)\n",
    "            denom = abs(g_num) + abs(G_[idx]) + 1e-8\n",
    "            if denom > 1e-6:\n",
    "                rel = abs(G_[idx] - g_num) / denom\n",
    "                assert rel < 1e-4, f'{nama[pi]}{idx}: analitik {G_[idx]:.6f} vs numerik {g_num:.6f} (rel {rel:.1e})'\n",
    "                cek += 1\n",
    "            it.iternext()\n",
    "            if cek >= 12:\n",
    "                break\n",
    "    return True\n",
    "assert _grad_check_rnn()\n",
    "print('✅ Latihan 8.1 benar! BPTT terverifikasi numerik (semua parameter).')\n",
))

cells.append(code(
    "def generate_rnn(params, seed_str, n_char, temp, rng):\n",
    "    \"\"\"Generate karakter demi karakter; hidden state membawa konteks penuh.\"\"\"\n",
    "    Wx, Wh, Wy, bh, by = params\n",
    "    hidden = Wh.shape[0]\n",
    "    out = seed_str\n",
    "    ctx_ids = [c2i_lm[c] for c in seed_str[-CTX:]]\n",
    "    h = np.zeros(hidden)\n",
    "    for cid in ctx_ids:                        # \"hangatkan\" state dengan seed\n",
    "        h = np.tanh(onehot_batch([cid], C_lm) @ Wx + h @ Wh.T + bh)\n",
    "    for _ in range(n_char):\n",
    "        logits = (h @ Wy + by).ravel()\n",
    "        p = np.exp((logits - logits.max()) / temp)\n",
    "        p = p / p.sum()\n",
    "        nxt = int(rng.choice(C_lm, p=p))\n",
    "        out += i2c_lm[nxt]\n",
    "        h = np.tanh(onehot_batch([nxt], C_lm) @ Wx + h @ Wh.T + bh)\n",
    "    return out\n",
    "\n",
    "rng_g = np.random.default_rng(5)\n",
    "for t in (0.3, 0.7, 1.2):\n",
    "    print(f'--- RNN T={t} ---')\n",
    "    print(generate_rnn(model_rnn['params'], 'men', 140, t, rng_g))\n",
    "    print()\n",
    "print('Bandingkan dengan bigram (Bagian 7): RNN menghasilkan potongan kata yang',\n",
    "      'jauh lebih utuh karena konteksnya lebih panjang.')\n",
))

# ============================ BAGIAN 9 ============================
cells.append(md(
    "## Bagian 9 — Vanishing Gradient: Sigmoid vs Tanh",
    "",
    "Kenapa RNN modern pakai `tanh`/`LSTM`/`GRU`, bukan sigmoid? Jawabannya ada di",
    "**turunan aktivasi** sepanjang backprop waktu: gradien dikalikan berulang kali",
    "oleh `W_hᵀ · diag(aktivasi')`. Kalau faktor itu < 1, gradien meluruh eksponensial",
    "→ konteks jauh \"tak pernah belajar\".",
))

cells.append(code(
    "def bptt_norm(act, T=30, seed=0, radius=0.9):\n",
    "    \"\"\"Simulasi ||gradien|| saat mengalir ke belakang T langkah waktu.\n",
    "    W_h dinormalisasi (radius 0.9) supaya yang dibedakan murni turunan aktivasi.\"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "    Wh = np.abs(rng.normal(0, 0.35, (20, 20)))\n",
    "    Wh = Wh / np.linalg.norm(Wh, 2) * radius\n",
    "    g = np.full(20, 0.5)\n",
    "    out = []\n",
    "    for _ in range(T):\n",
    "        if act == 'tanh':\n",
    "            deriv = 1 - np.tanh(np.linspace(-1.5, 1.5, 20)) ** 2\n",
    "        else:  # sigmoid\n",
    "            s = 1 / (1 + np.exp(-np.linspace(-2.5, 2.5, 20)))\n",
    "            deriv = s * (1 - s)\n",
    "        g = Wh @ (g * deriv)\n",
    "        out.append(float(g.mean()))\n",
    "    return out\n",
    "\n",
    "norm_tanh = bptt_norm('tanh')\n",
    "norm_sig = bptt_norm('sigmoid')\n",
    "plt.semilogy(norm_tanh, label='tanh')\n",
    "plt.semilogy(norm_sig, label='sigmoid')\n",
    "plt.xlabel('langkah waktu ke belakang'); plt.ylabel('||gradien|| rata-rata')\n",
    "plt.title('Vanishing gradient: keduanya meluruh, sigmoid jauh lebih cepat')\n",
    "plt.legend(); plt.grid(alpha=0.3); plt.show()\n",
    "\n",
    "assert norm_sig[-1] < norm_tanh[-1], 'sigmoid harus meluruh lebih cepat'\n",
    "assert norm_tanh[-1] < 1e-4, 'tanh juga meluruh (konteks 30 langkah)'\n",
    "print(f'✅ T=30: tanh {norm_tanh[-1]:.1e} vs sigmoid {norm_sig[-1]:.1e}')\n",
    "print('   Kedua RNN polos kehilangan konteks jauh — itulah mengapa LSTM/GRU (gate)',\n",
    "      'dan Transformer (attention) diciptakan.')\n",
))

# ============================ BAGIAN 10 ============================
cells.append(md(
    "## Bagian 10 — Menuju Transformer & Keras (Pemetaan Konsep)",
    "",
    "Semua yang kamu bangun manual punya padanan langsung di library modern:",
    "",
    "| Yang kamu tulis | Di Keras / LLM |",
    "|---|---|",
    "| `bangun_vocab` + `encode` | `Tokenizer` / **BPE** (GPT, LLaMA) |",
    "| `train_skipgram` (W_in) | `layers.Embedding` pre-trained (word2vec, GloVe) |",
    "| `fitur_avg` | pooling / embedding dokumen (RAG!) |",
    "| bigram + temperature | next-token prediction + `temperature` di LLM API |",
    "| RNN BPTT | `layers.SimpleRNN` / `LSTM` / `GRU` |",
    "| vanishing gradient (Bagian 9) | alasan lahirnya **Transformer** (Bab 9) |",
    "",
    "Kenapa Transformer menggantikan RNN? (1) **Paralel** — tidak menunggu langkah waktu,",
    "(2) **Akses langsung** ke semua token (self-attention) — tidak ada gradien yang harus",
    "berjalan 30 langkah. RNN tetap berguna sebagai konsep & untuk data kecil/streaming.",
))

cells.append(code(
    "# Peta numpy -> Keras: hal yang sama, 10 baris (jalankan kalau TF terpasang)\n",
    "try:\n",
    "    import tensorflow as tf\n",
    "    from tensorflow import keras\n",
    "    from tensorflow.keras import layers\n",
    "\n",
    "    # Embedding + GlobalAveragePooling = 'fitur_avg'-mu, dipercepat GPU\n",
    "    model_tf = keras.Sequential([\n",
    "        layers.Embedding(input_dim=len(vocab6), output_dim=16),\n",
    "        layers.GlobalAveragePooling1D(),\n",
    "        layers.Dense(1, activation='sigmoid'),\n",
    "    ])\n",
    "    model_tf.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])\n",
    "    print('Keras: Embedding -> GAP -> Dense = pipeline fitur_avg + logreg yang kamu tulis manual.')\n",
    "\n",
    "    # SimpleRNN = RNN Elman Bagian 8\n",
    "    model_rnn_k = keras.Sequential([\n",
    "        layers.SimpleRNN(32, input_shape=(CTX, C_lm)),\n",
    "        layers.Dense(C_lm, activation='softmax'),\n",
    "    ])\n",
    "    model_rnn_k.compile(optimizer='adam', loss='sparse_categorical_crossentropy')\n",
    "    print('Keras: SimpleRNN(32) = RNN-mu; LSTM/GRU = varian dengan gate utk konteks panjang.')\n",
    "except ImportError:\n",
    "    print('TensorFlow belum terpasang — konsepnya tetap valid:')\n",
    "    print('  layers.Embedding ~ W_in-mu; GlobalAveragePooling1D ~ fitur_avg-mu;')\n",
    "    print('  SimpleRNN ~ RNN-mu; temperature di LLM API ~ sample_bigram/generate_rnn-mu.')\n",
    "    print('  Semua yang kamu butuh untuk MEMAHAMINYA sudah ada di lab ini.')\n",
))

cells.append(md(
    "**Refleksi terakhir:**",
    "",
    "1. Jelaskan ke teman: kenapa embedding menang atas one-hot untuk klasifikasi sentimen?",
    "   Gunakan kata *dimensi kompak*, *makna*, dan *generalisasi*.",
    "2. Bagian 8: kenapa RNN mengalahkan bigram? Apa yang direpresentasikan hidden state?",
    "3. Kenapa temperature rendah membuat teks repetitif? Kapan kamu memilih T rendah",
    "   vs tinggi saat memakai LLM API (Bab 11)?",
    "4. Sebut 2 kelemahan RNN yang membuat Transformer unggul (Bab 9).",
))

# ============================ PENUTUP ============================
cells.append(md(
    "## 🏁 Penutup Lab",
    "",
    "**Yang sudah kamu bangun dari nol:** tokenizer + vocabulary + padding/OOV, korpus",
    "ko-okurensi, skip-gram dengan negative sampling (gradien terverifikasi numerik),",
    "pembuktian klaster semantik via purity + PCA, klasifikasi sentimen dengan fitur",
    "embedding, char-level bigram LM dengan temperature sampling, RNN dengan BPTT penuh",
    "(gradient check) yang mengalahkan bigram, dan demonstrasi vanishing gradient.",
    "",
    "**Lanjut:** `02_kuis_nlp_text.ipynb` → `project-starter-lm-mini/` →",
    "`cheatsheet-nlp-text.md`.",
))

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
