"""Generate 02_kuis_ml_produksi.ipynb for Bab 8."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "02_kuis_ml_produksi.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


cells = [
    md(
        "# 📝 Kuis Bab 8 - ML Produksi",
        "",
        "12 soal (8 pilihan ganda + 4 coding), total **23 poin**. Penilaian otomatis di cell terakhir.",
        "",
        "**Aturan:** kerjakan tanpa membuka materi. Soal coding: isi di bawah `# TODO`,",
        "lalu jalankan cell penilaian di bawah. Boleh pakai NumPy.",
    ),
    md("## Bagian A - Pilihan Ganda (isi `JAWABAN`)"),
    code(
        "# Isi jawaban pilihan ganda di sini, contoh: JAWABAN[1] = 'a'\n",
        "\n",
        "JAWABAN = {\n",
        "    1: None,\n",
        "    2: None,\n",
        "    3: None,\n",
        "    4: None,\n",
        "    5: None,\n",
        "    6: None,\n",
        "    7: None,\n",
        "    8: None,\n",
        "}",
    ),
    md(
        "### Soal 1 - Rasio split yang jujur",
        "",
        "Kamu menyetel threshold klasifikasi. Data yang mana yang paling SAH dipakai",
        "untuk memilih nilai threshold?",
        "",
        "- a) test set - supaya angka test langsung bagus",
        "- b) training set - datanya paling banyak",
        "- c) calib/validation set - keputusan model diambil di sini, test tetap jujur",
        "- d) semua data digabung - makin banyak data makin akurat",
    ),
    md(
        "### Soal 2 - Model bagus tapi kalah baseline",
        "",
        "RMSE model-mu di test = 6.7. Baseline HAM (prediksi konstan mean train) di data",
        "yang sama: RMSE 4.8. Kesimpulan yang PALING tepat:",
        "",
        "- a) RMSE 6.7 cukup baik asal konvergen saat training",
        "- b) Model gagal mengalahkan baseline -> skill score negatif -> TOLAK model,",
        "  pakai baseline sampai ada perbaikan nyata",
        "- c) Baseline harus dihapus dari laporan karena mempermalukan model",
        "- d) RMSE bukan metrik yang cocok; ganti ke accuracy",
    ),
    md(
        "### Soal 3 - Bocor saat normalisasi",
        "",
        "Pipeline-mu: normalisasi fitur dengan `StandardScaler` yang di-fit pada SELURUH",
        "dataset, baru di-split train/test. Masalah utamanya:",
        "",
        "- a) Tidak ada masalah - normalisasi memang boleh lihat semua data",
        "- b) Statistik scaler (mean/std) memuat informasi test - data leakage; fit scaler",
        "  HARUS di train saja, lalu transform ke calib/test",
        "- c) Hanya masalah kalau fitur punya outlier",
        "- d) Masalah hanya muncul di deep learning",
    ),
    md(
        "### Soal 4 - F1 dari confusion matrix",
        "",
        "Confusion matrix: TP=3, FP=1, FN=2. Nilai F1:",
        "",
        "- a) 0.75 (itu precision)",
        "- b) 0.60 (itu recall)",
        "- c) 0.667 - F1 = 2PR/(P+R) = 2·0.75·0.6/1.35 - harmonic mean dari P dan R",
        "- d) 0.675 (rata-rata aritmetika P dan R)",
    ),
    md(
        "### Soal 5 - Metrik untuk screening medis",
        "",
        "Sistem screening penyakit langka (prevalence 1%): satu pasien yang TERLEWAT",
        "jauh lebih mahal daripada satu alarm palsu. Threshold harus dipilih untuk",
        "memaksimalkan:",
        "",
        "- a) precision - menghindari alarm palsu",
        "- b) accuracy - paling seimbang",
        "- c) recall - mengurangi pasien terlewat (FN), biaya FP ditanggung proses",
        "  verifikasi lanjutan",
        "- d) specificity saja",
    ),
    md(
        "### Soal 6 - Arti ECE tinggi",
        "",
        "Model probabilistik punya ECE 0.20 (20%). Artinya:",
        "",
        "- a) Akurasi model 80% - ECE memang sinonim akurasi",
        "- b) Prediksi probabilitasnya sistematis tak cocok kenyataan (mis. bilang 90%",
        "  tapi benar 70%) - perlu kalibrasi ulang (mis. Platt scaling)",
        "- c) Model overfit ke data train",
        "- d) ECE tinggi wajar di semua model modern - abaikan",
    ),
    md(
        "### Soal 7 - Urutan backprop GAN",
        "",
        "Saat memperbarui Generator dengan loss non-saturating `-log D(G(z))`, gradien",
        "yang benar:",
        "",
        "- a) Hitung gradien terhadap parameter D saja - G tidak butuh gradien",
        "- b) Backprop MELEWATI jaringan D (yang dibekukan) sampai ke output G,",
        "  lalu update parameter G - rantai: logit D → skor D → x_fake → parameter G",
        "- c) Update D dan G bersamaan dari loss yang sama",
        "- d) Cukup turunkan loss G dengan mengubah output D langsung",
    ),
    md(
        "### Soal 8 - Round-trip test",
        "",
        "Model sudah di-save ke disk. Sebelum artefak dipakai di serving, langkah wajib:",
        "",
        "- a) Tidak perlu - save yang benar pasti load dengan benar",
        "- b) Load kembali lalu bandingkan prediksi SEBELUM dan SESUDAH round-trip",
        "  pada data uji - harus identik bit-per-bit",
        "- c) Cukup cek ukuran file tidak nol",
        "- d) Jalankan ulang training untuk memastikan hasilnya sama",
    ),
    md("## Bagian B - Coding"),
    md(
        "### Soal 9 - `rmse_mae` (3 poin)",
        "",
        "`rmse_mae(y_true, y_pred)` → tuple `(rmse, mae)`:",
        "",
        "- `rmse = sqrt(mean((y_true − y_pred)²))`",
        "- `mae  = mean(|y_true − y_pred|)`",
        "",
        "Contoh: `y_true=[1,2]`, `y_pred=[2,4]` → `(1.5811..., 1.5)`.",
    ),
    code(
        "import numpy as np\n",
        "\n",
        "def rmse_mae(y_true, y_pred):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# r, m = rmse_mae(np.array([1., 2.]), np.array([2., 4.]))\n",
        "# print(r, m)  # ~1.5811 dan 1.5"
    ),
    md(
        "### Soal 10 - `confusion` (3 poin)",
        "",
        "`confusion(y_true01, y_score, thr)` → dict `{'tp', 'fp', 'fn', 'tn'}`.",
        "Prediksi positif jika `y_score >= thr` (perhatikan: `>=`, bukan `>`).",
        "Semua nilai int.",
    ),
    code(
        "def confusion(y_true01, y_score, thr):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# cm = confusion([1, 0, 1, 0], [0.9, 0.8, 0.3, 0.1], 0.5)\n",
        "# print(cm)  # {'tp': 1, 'fp': 1, 'fn': 1, 'tn': 1}"
    ),
    md(
        "### Soal 11 - `prf` (5 poin)",
        "",
        "`prf(cm)` → dict `{'precision', 'recall', 'f1'}` dari confusion matrix:",
        "",
        "- `precision = tp/(tp+fp)`, `recall = tp/(tp+fn)`",
        "- `f1 = 2·P·R/(P+R)` - harmonic mean",
        "- Pembagi nol → metrik = 0.0 (JANGAN crash - konvensi produksi)",
        "",
        "Contoh: `{'tp':3,'fp':1,'fn':2,'tn':4}` → P=0.75, R=0.6, F1≈0.6667.",
    ),
    code(
        "def prf(cm):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# m = prf({'tp': 3, 'fp': 1, 'fn': 2, 'tn': 4})\n",
        "# print(m)  # {'precision': 0.75, 'recall': 0.6, 'f1': 0.666...}"
    ),
    md(
        "### Soal 12 - `ece_bin` (4 poin)",
        "",
        "`ece_bin(y_true01, p, n_bins=10)` → ECE (float):",
        "",
        "- Kelompokkan prediksi: `idx = min(int(p · n_bins), n_bins − 1)`",
        "- Per bin: `conf = mean(p)`, `acc = mean(label)` (bin kosong: lewati)",
        "- `ECE = Σ (n_bin / n_total) · |acc − conf|`",
        "",
        "Contoh: `y=[1,0,1,0]`, `p=[0.9,0.1,0.8,0.2]`, 10 bin → ECE = 0.15.",
    ),
    code(
        "def ece_bin(y_true01, p, n_bins=10):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# e = ece_bin(np.array([1, 0, 1, 0]), np.array([0.9, 0.1, 0.8, 0.2]), 10)\n",
        "# print(e)  # 0.15"
    ),
    md("## 🧮 Penilaian Otomatis"),
    code(
        "import numpy as np\n",
        "\n",
        "total_bobot = 23\n",
        "\n",
        "\n",
        "def jalankan_kuis():\n",
        "    skor = 0\n",
        "    rincian = []\n",
        "\n",
        "    def cek_pilihan(nomor, kunci, bobot=1):\n",
        "        nonlocal skor\n",
        "        benar = JAWABAN.get(nomor) == kunci\n",
        "        skor += bobot if benar else 0\n",
        "        rincian.append((nomor, benar))\n",
        "\n",
        "    def cek_kode(nomor, uji, bobot=1):\n",
        "        nonlocal skor\n",
        "        benar = False\n",
        "        try:\n",
        "            benar = bool(uji())\n",
        "        except Exception as e:\n",
        "            print(f'  soal {nomor}: error -> {type(e).__name__}: {e}')\n",
        "        skor += bobot if benar else 0\n",
        "        rincian.append((nomor, benar))\n",
        "\n",
        "    def approx(a, b, tol=1e-6):\n",
        "        return np.allclose(np.asarray(a, dtype=float), np.asarray(b, dtype=float), atol=tol)\n",
        "\n",
        "    def _safe(nama, *args):\n",
        "        fn = globals().get(nama)\n",
        "        if fn is None:\n",
        "            return None\n",
        "        try:\n",
        "            return fn(*args)\n",
        "        except Exception:\n",
        "            return None\n",
        "\n",
        "    cek_pilihan(1, 'c')\n",
        "    cek_pilihan(2, 'b')\n",
        "    cek_pilihan(3, 'b')\n",
        "    cek_pilihan(4, 'c')\n",
        "    cek_pilihan(5, 'c')\n",
        "    cek_pilihan(6, 'b')\n",
        "    cek_pilihan(7, 'b')\n",
        "    cek_pilihan(8, 'b')\n",
        "\n",
        "    # Soal 9 - rmse_mae\n",
        "    def uji9():\n",
        "        r, m = rmse_mae(np.array([1., 2.]), np.array([2., 4.]))\n",
        "        assert abs(r - np.sqrt(2.5)) < 1e-9 and abs(m - 1.5) < 1e-9\n",
        "        r2_, m2_ = rmse_mae(np.array([0., 0.]), np.array([3., 4.]))\n",
        "        assert abs(r2_ - np.sqrt(12.5)) < 1e-9 and abs(m2_ - 3.5) < 1e-9\n",
        "        r3, m3 = rmse_mae(np.array([5.]), np.array([5.]))\n",
        "        assert r3 == 0.0 and m3 == 0.0, 'prediksi sempurna -> nol'\n",
        "        return True\n",
        "    cek_kode(9, uji9, bobot=3)\n",
        "\n",
        "    # Soal 10 - confusion\n",
        "    def uji10():\n",
        "        cm = confusion(np.array([1, 0, 1, 0]), np.array([0.9, 0.8, 0.3, 0.1]), 0.5)\n",
        "        assert cm == {'tp': 1, 'fp': 1, 'fn': 1, 'tn': 1}\n",
        "        cm2 = confusion(np.array([0]), np.array([0.5]), 0.5)\n",
        "        assert cm2['fp'] == 1, 'tepat di threshold dihitung POSITIF (>=)'\n",
        "        cm3 = confusion(np.array([1, 0, 0, 0]), np.array([1.0, 0.0, 0.4, 0.2]), 0.5)\n",
        "        assert cm3 == {'tp': 1, 'fp': 0, 'fn': 0, 'tn': 3}\n",
        "        return True\n",
        "    cek_kode(10, uji10, bobot=3)\n",
        "\n",
        "    # Soal 11 - prf\n",
        "    def uji11():\n",
        "        m = prf({'tp': 3, 'fp': 1, 'fn': 2, 'tn': 4})\n",
        "        assert approx(m['precision'], 0.75) and approx(m['recall'], 0.6)\n",
        "        assert approx(m['f1'], 2 * 0.75 * 0.6 / 1.35)\n",
        "        m0 = prf({'tp': 0, 'fp': 0, 'fn': 5, 'tn': 5})\n",
        "        assert m0['precision'] == 0.0 and m0['recall'] == 0.0 and m0['f1'] == 0.0, \\\n",
        "            'pembagi nol -> 0.0, bukan crash'\n",
        "        m1 = prf({'tp': 2, 'fp': 0, 'fn': 0, 'tn': 1})\n",
        "        assert m1['precision'] == 1.0 and m1['recall'] == 1.0 and m1['f1'] == 1.0\n",
        "        return True\n",
        "    cek_kode(11, uji11, bobot=5)\n",
        "\n",
        "    # Soal 12 - ece_bin\n",
        "    def uji12():\n",
        "        e = ece_bin(np.array([1, 0, 1, 0]), np.array([0.9, 0.1, 0.8, 0.2]), 10)\n",
        "        assert abs(e - 0.15) < 1e-9, f'dapat {e}'\n",
        "        e2 = ece_bin(np.array([1, 1, 1, 1]), np.array([0.95, 0.85, 0.75, 0.55]), 10)\n",
        "        # semua label=1: selisih |acc-conf| per bin = 0.05+0.15+0.25+0.45, tiap bin bobot 0.25\n",
        "        assert abs(e2 - 0.25 * (0.05 + 0.15 + 0.25 + 0.45)) < 1e-9, f'dapat {e2}'\n",
        "        e3 = ece_bin(np.array([1, 0]), np.array([1.0, 0.0]), 10)\n",
        "        assert abs(e3 - 0.0) < 1e-9, 'p=1.0 masuk bin terakhir, prediktor sempurna -> ECE 0'\n",
        "        return True\n",
        "    cek_kode(12, uji12, bobot=4)\n",
        "\n",
        "    print('=' * 46)\n",
        "    for nomor, benar in rincian:\n",
        "        print(f'  Soal {nomor:>2}: {\"BENAR\" if benar else \"salah\"}')\n",
        "    print('=' * 46)\n",
        "    print(f'SKOR AKHIR: {skor}/{total_bobot}')\n",
        "    if skor == total_bobot:\n",
        "        print('Sempurna! Lanjut ke project starter.')\n",
        "    elif skor >= 18:\n",
        "        print('Bagus! Review soal yang salah, lalu lanjut.')\n",
        "    else:\n",
        "        print('Ulangi bagian terkait di lab, coba lagi besok.')\n",
        "\n",
        "jalankan_kuis()",
    ),
    md(
        "---",
        "",
        "Sudah mencoba serius? Bandingkan pendekatanmu dengan `03_kunci_jawaban_kuis_ml_produksi.ipynb`",
        "- fokus pada intuisi di balik tiap jawaban."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
