"""Generate 03_kunci_jawaban_kuis_computer_vision.ipynb for Bab 5."""
import json
from pathlib import Path

OUT = Path("AI-Engineering-Curriculum/05-Computer-Vision/03_kunci_jawaban_kuis_computer_vision.ipynb")


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


cells = [
    md(
        "# 🔑 Kunci Jawaban — Kuis Bab 5 (Computer Vision)",
        "",
        "> **Buka file ini HANYA SETELAH** mencoba kuis sendiri. Membaca jawaban",
        "> sebelum berjuang = nol pembelajaran (ilusi kompetensi).",
        "",
        "Untuk tiap soal: jawaban → **kenapa** → versi idiomatik. Fokus belajar ada di bagian *kenapa*.",
    ),
    md("## Bagian A — Pilihan Ganda"),
    md(
        "### Soal 1 — Jawaban: **b) 14x14**",
        "",
        "Rumus ukuran output konvolusi: `floor((H + 2·pad − k) / stride) + 1`.",
        "Dengan H=32, k=5, pad=0, stride=2 → `floor((32 − 5)/2) + 1 = floor(27/2) + 1 = 13 + 1 = 14`.",
        "",
        "Kenapa opsi lain menjebak:",
        "",
        "- **a) 16x16** — hanya membagi input dengan stride (32/2), lupa mengurangi",
        "  ukuran kernel dulu sebelum membagi.",
        "- **c) 15x15** — rumus hampir benar tapi membulatkan ke atas: `27/2 = 13.5`",
        "  → ceil 14, +1 = 15. Yang benar `floor(13.5) = 13`, +1 = **14**.",
        "- **d) 28x28** — rumus benar tapi lupa stride (pad=0, stride=1).",
        "",
        "Perhatikan pola: **stride membulatkan ke bawah** — piksel terakhir yang tidak",
        "membentuk jendela penuh dibiarkan jatuh.",
    ),
    code(
        "def ukuran_output(H, k, pad=0, stride=1):\n",
        "    return (H + 2 * pad - k) // stride + 1\n",
        "\n",
        "print('32, k=5, stride=2 ->', ukuran_output(32, 5, 0, 2))   # 14\n",
        "print('32, k=3            ->', ukuran_output(32, 3))          # 30\n",
        "print('32, k=3, pad=1     ->', ukuran_output(32, 3, 1))     # 32 ('same' utk kernel ganjil)",
    ),
    md(
        "### Soal 2 — Jawaban: **b) invarian translasi-kecil + mengecilkan representasi**",
        "",
        "Max-pool 2x2 mengambil nilai terbesar tiap jendela → kalau fitur bergeser sedikit,",
        "nilai max yang sama tetap menang. Itulah **invarian translasi-kecil**. Bonusnya:",
        "ukuran turun 4× (2× per sisi) → komputasi layer berikutnya jauh lebih ringan.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** pooling **tidak punya parameter** yang dilatih — dia operasi tetap.",
        "- **c)** pooling bukan aktivasi; ReLU tetap dipasang terpisah setelah conv.",
        "- **d)** pooling adalah operasi spasial untuk peta fitur (output conv),",
        "  bukan sesuatu yang dipasang setelah dense layer.",
    ),
    code(
        "import numpy as np\n",
        "\n",
        "x = np.arange(16, dtype=float).reshape(4, 4)\n",
        "pooled = x.reshape(2, 2, 2, 2).max(axis=(1, 3))\n",
        "print('input:\\n', x)\n",
        "print('max-pool 2x2:\\n', pooled)   # [[ 5., 7.], [13., 15.]]\n",
        "# Geser fitur 1 piksel dalam jendela -> max yang sama tetap menang.",
    ),
    md(
        "### Soal 3 — Jawaban: **c) flip vertikal merusak label MNIST**",
        "",
        "Digit yang dicerminkan atas-bawah berubah identitas: **6 ↔ 9**, 2 jadi bentuk yang",
        "tidak pernah ditulis manusia, dst. Label 6 yang di-flip jadi terlihat seperti 9 —",
        "model dipaksa mempelajari hubungan **gambar↔label yang salah**.",
        "",
        "Kenapa lainnya aman: rotasi ±10° dan shift 1–2 piksel tidak mengubah identitas digit",
        "(itu sebabnya `random_shift` di lab aman-label), dan noise ringan hanya menambah",
        "variasi tanpa mengganti bentuk.",
        "",
        "Aturan umum: augmentasi harus **menjaga label tetap benar**. Flip horizontal aman",
        "untuk kucing (kucing cermin masih kucing), tidak aman untuk digit & teks.",
    ),
    md(
        "### Soal 4 — Jawaban: **b) pre-trained + freeze + head + augmentasi**",
        "",
        "800 gambar untuk 2 kelas = kasus buku teks \"data sedikit\" → pakai fitur umum",
        "yang sudah dipelajari ImageNet (tepi, tekstur, bentuk), lalu latih hanya",
        "classifier head. Augmentasi memperbanyak variasi efektif data.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** CNN besar + data 800 = resep overfitting; tidak ada cukup data untuk fitur dari nol.",
        "- **c)** unfreeze semua + lr besar = **catastrophic forgetting** — bobot pre-trained",
        "  yang bagus langsung hancur oleh gradien besar dari data kecil.",
        "- **d)** printer error vs normal adalah klasifikasi; mengubah jadi regresi hanya",
        "  menambah masalah tanpa manfaat.",
    ),
    md("## Bagian B — Coding"),
    md(
        "### Soal 5 — `conv_valid` (3 poin)",
        "",
        "Pola inti konvolusi cross-correlation (yang dipakai framework ML): geser jendela",
        "sebesar kernel, kalikan elemen-wise, jumlahkan. Loop ganda di posisi output,",
        "bukan di dalam kernel — jauh lebih sederhana dan bentuk ini yang nanti dipercepat",
        "`sliding_window_view` + `tensordot` di lab Bagian 4.",
        "",
        "Di Keras, layer `Conv2D` melakukan tepat ini per channel/filter — hanya saja",
        "dengan ribuan filter sekaligus."
    ),
    code(
        "import numpy as np\n",
        "\n",
        "def conv_valid(img, K):\n",
        "    img = np.asarray(img, dtype=float); K = np.asarray(K, dtype=float)\n",
        "    H, W = img.shape; kh, kw = K.shape\n",
        "    out = np.zeros((H - kh + 1, W - kw + 1))\n",
        "    for i in range(out.shape[0]):\n",
        "        for j in range(out.shape[1]):\n",
        "            out[i, j] = np.sum(img[i:i + kh, j:j + kw] * K)\n",
        "    return out\n",
        "\n",
        "img = np.arange(9, dtype=float).reshape(3, 3)\n",
        "print(conv_valid(img, np.ones((2, 2))))   # [[ 8., 12.], [20., 24.]]\n",
        "print(conv_valid(img, np.eye(2)))         # [[4., 6.], [10., 12.]]",
    ),
    md(
        "### Soal 6 — `ukuran_output` (2 poin)",
        "",
        "Satu rumus yang harus jadi refleks: `(H + 2·pad − k) // stride + 1`.",
        "Poin tersembunyi: **pembagian bulat `//`**, bukan `/` — ukuran output harus integer,",
        "dan stride yang tidak membagi habis membulatkan ke bawah.",
        "",
        "Kasus spesial yang layak dihafal: `pad=(k−1)/2` dengan stride 1 → ukuran tetap",
        "(inilah `padding='same'` di Keras untuk kernel ganjil)."
    ),
    code(
        "def ukuran_output(H, k, pad=0, stride=1):\n",
        "    return (H + 2 * pad - k) // stride + 1\n",
        "\n",
        "print(ukuran_output(32, 3), ukuran_output(32, 3, 1),\n",
        "      ukuran_output(32, 3, 0, 2), ukuran_output(28, 3, 1, 2), ukuran_output(8, 5))\n",
        "# 30 32 15 14 4",
    ),
    md(
        "### Soal 7 — `maxpool2x2` (3 poin)",
        "",
        "Kunci: reshape ke `(H/2, 2, W/2, 2)` lalu max di **dua sumbu dalam sekaligus**",
        "`axis=(1, 3)`. Ini versi tanpa-loop dari backward di Soal 8 — dan bentuk yang",
        "sama dipakai di `Pool2x2` lab Bagian 5 untuk batch `(N, H, W)`.",
    ),
    code(
        "def maxpool2x2(x):\n",
        "    x = np.asarray(x, dtype=float)\n",
        "    H, W = x.shape\n",
        "    return x.reshape(H // 2, 2, W // 2, 2).max(axis=(1, 3))\n",
        "\n",
        "x = np.arange(16, dtype=float).reshape(4, 4)\n",
        "print(maxpool2x2(x))   # [[ 5., 7.], [13., 15.]]",
    ),
    md(
        "### Soal 8 — `maxpool2x2_backward` (4 poin)",
        "",
        "Prinsip: gradien hanya mengalir ke posisi yang **menang** di forward (argmax),",
        "posisi lain 0 — kalau semua posisi ikut dapat gradien, layer sebelumnya akan",
        "\"dihukum\" untuk fitur yang tidak dipakai. Konsekuensinya `dX.sum() == dOut.sum()`.",
        "",
        "Yang dinilai: (1) hanya argmax yang dapat gradien, (2) nilainya = dOut jendela itu,",
        "(3) seri ditangani sebagai subgradien (pilih satu pemenang, total tetap benar).",
        "Bentuk ini persis `maxpool2x2_backward` di lab/project — `np.argmax` flat pertama",
        "yang di-unravel = pemenang seri yang deterministik."
    ),
    code(
        "def maxpool2x2_backward(dOut, x):\n",
        "    x = np.asarray(x, dtype=float)\n",
        "    H, W = x.shape\n",
        "    dX = np.zeros_like(x)\n",
        "    for i in range(H // 2):\n",
        "        for j in range(W // 2):\n",
        "            win = x[2 * i:2 * i + 2, 2 * j:2 * j + 2]\n",
        "            idx = np.unravel_index(np.argmax(win), win.shape)\n",
        "            dX[2 * i + idx[0], 2 * j + idx[1]] += dOut[i, j]\n",
        "    return dX\n",
        "\n",
        "x = np.arange(16, dtype=float).reshape(4, 4)\n",
        "dOut = np.array([[1., 2.], [3., 4.]])\n",
        "dX = maxpool2x2_backward(dOut, x)\n",
        "print(dX)\n",
        "print('total gradien:', dX.sum(), '(= dOut.sum())')",
    ),
    md(
        "### Soal 9 — `shift_zero` (3 poin)",
        "",
        "Dua hal yang dinilai: (1) geser dengan **slice saling-melengkapi** — sumber dan",
        "tujuan dihitung dari dy/dx yang sama sehingga dy=dx=0 mengembalikan salinan persis;",
        "(2) area kosong diisi 0 **dan input tidak berubah** (selalu buat array baru).",
        "Mutasi input adalah bug klasik augmentasi: data asli ikut \"bergeser\" sepanjang epoch.",
        "",
        "Di lab Bagian 7, fungsi ini jadi `random_shift` — satu-satunya augmentasi di",
        "eksperimen invarian translasi karena aman-label untuk Bars.",
    ),
    code(
        "def shift_zero(img, dy, dx):\n",
        "    img = np.asarray(img, dtype=float)\n",
        "    H, W = img.shape\n",
        "    out = np.zeros_like(img)\n",
        "    ys, xs = slice(max(0, -dy), min(H, H - dy)), slice(max(0, -dx), min(W, W - dx))\n",
        "    yd, xd = slice(max(0, dy), min(H, H + dy)), slice(max(0, dx), min(W, W + dx))\n",
        "    out[yd, xd] = img[ys, xs]\n",
        "    return out\n",
        "\n",
        "g = np.arange(16, dtype=float).reshape(4, 4)\n",
        "print(shift_zero(g, 1, 0))    # baris 0 jadi 0, baris 1 = baris 0 asli\n",
        "print(shift_zero(g, 0, -1))   # semua bergeser kiri, kolom terakhir 0",
    ),
    md(
        "### Soal 10 — `filter_tepi_v` + `tepi_v_score` (4 poin)",
        "",
        "Kernel `[[-1, 0, 1]]` per baris menjumlahkan (kolom kanan − kolom kiri): di area",
        "datar keduanya kancel → 0; di transisi gelap→terang hasilnya besar positif.",
        "Itulah definisi **tepi vertikal**: bukan warna tertentu, tapi *perubahan* antar-kolom.",
        "Layer conv pertama di CNN pre-trained belajar kernel-kernel seperti ini sendiri",
        "dari data — dan itu poin transfer learning di Soal 4.",
    ),
    code(
        "def filter_tepi_v():\n",
        "    return np.array([[-1., 0., 1.], [-1., 0., 1.], [-1., 0., 1.]])\n",
        "\n",
        "def tepi_v_score(img):\n",
        "    return conv_valid(img, filter_tepi_v())\n",
        "\n",
        "img = np.zeros((5, 5)); img[:, 3:] = 1.0   # gelap kiri, terang kanan\n",
        "print(np.round(tepi_v_score(img), 2))\n",
        "# 3.0 di kolom 1-2 (transisi), 0 di kolom lainnya",
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
