"""Generate 03_kunci_jawaban_kuis_time_series.ipynb for Bab 7."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "03_kunci_jawaban_kuis_time_series.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


cells = [
    md(
        "# 🔑 Kunci Jawaban - Kuis Bab 7 (Time Series)",
        "",
        "> **Buka file ini HANYA SETELAH** mencoba kuis sendiri. Membaca jawaban",
        "> sebelum berjuang = nol pembelajaran (ilusi kompetensi).",
        "",
        "Untuk tiap soal: jawaban → **kenapa** → kode referensi. Fokus belajar ada di bagian *kenapa*.",
    ),
    md("## Bagian A - Pilihan Ganda"),
    md(
        "### Soal 1 - Jawaban: **c) 800 titik PERTAMA untuk train, 200 TERAKHIR untuk val**",
        "",
        "Time series punya urutan waktu - split harus menjaga urutan itu: latih di masa lalu,",
        "nilai di masa depan. Ini simulasi paling jujur dari pemakaian nyata (model tidak pernah",
        "melihat masa depan saat dipakai).",
        "",
        "Kenapa opsi lain menjebak:",
        "",
        "- **a)** shuffle = titik masa depan bocor ke training (data leakage temporal). Model",
        "  'menghafal' jawaban dari masa depan - skor val terlihat bagus tapi bodoh saat dipakai.",
        "- **b)** default `shuffle=True` di kebanyakan API - kesalahan paling umum pemula.",
        "- **d)** kebalikan arah waktu: melatih di masa depan, menguji di masa lalu. Sama ilegalnya.",
        "",
        "Catatan lab Bagian 2: split acak tetap sah untuk data IID (Bab 3) - yang berubah di",
        "time series adalah asumsi datanya, bukan aturannya.",
    ),
    md(
        "### Soal 2 - Jawaban: **b) Model gagal mengalahkan baseline**",
        "",
        "Baseline naive = 5.1, LSTM = 15.8. Model yang lebih buruk dari baseline belum layak",
        "dipakai - ia justru menambah noise. Langkah debug: (1) cek apakah series punya pola",
        "yang bisa dipelajari (ACF), (2) cek window terlalu kecil / terlalu besar, (3) cek",
        "noise dominan - kalau σ_noise ≫ sinyal, baseline memang hampir optimal.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** 'modern' bukan argumen - angka yang menentukan.",
        "- **c)** baseline justru WAJIB dilaporkan - ia bukti modelmu menambah nilai.",
        "- **d)** MAE sah untuk forecasting; masalahnya di model, bukan metrik.",
        "",
        "Bukti di lab Bagian 3: MAE naive 5.12 vs HAM 15.77 - bahkan baseline sederhana pun",
        "bisa mengalahkan model yang salah pilih.",
    ),
    md(
        "### Soal 3 - Jawaban: **b) y_true mendekati nol**",
        "",
        "MAPE membagi dengan |y_true|. Saat y_true → 0, pembagian meledak: satu titik dengan",
        "y_true = 0.001 bisa menyumbang error ribuan persen dan mendominasi rata-rata.",
        "Makanya data penjualan yang sering nol (produk baru, stok habis) tidak boleh dinilai",
        "dengan MAPE mentah.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** nilai negatif membuat MAPE janggal tapi tidak meledak; masalah utamanya nol.",
        "- **c)** y_pred besar hanya membuat error besar terbatas - tidak infinite.",
        "- **d)** jumlah titik tidak relevan dengan pembagian nol.",
        "",
        "Alternatif yang lebih aman: **sMAPE** (pembagi = |y_t| + |p_t|, dijaga epsilon) atau",
        "**MASE** (skala terhadap baseline naive). Di kuis, sMAPE diuji di Soal 11.",
    ),
    md(
        "### Soal 4 - Jawaban: **b) y = np.expm1(5.0)**",
        "",
        "`log1p(y) = log(1 + y)` punya invers eksak `expm1(z) = exp(z) - 1`.",
        "Pasangan ini dipilih justru karena inversnya numeris stabil untuk y kecil.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** `np.exp(5.0)` mengembalikan `exp(z)`, bukan `exp(z) - 1` - bias besar saat",
        "  z kecil (untuk z=5: exp(5)≈148.4 vs expm1(5)≈147.4 - selisih 1 unit!).",
        "- **c)** itu invers dari log(y), bukan log1p(y).",
        "- **d)** log monoton dan terdefinisi semua bilangan positif - selalu bisa dibalik.",
        "",
        "Urutan yang benar saat evaluasi (lab Bagian 6): transform → fit → prediksi di ruang",
        "log → **back-transform dulu** → baru hitung MAE di satuan asli. MAE log ≠ MAE asli.",
    ),
    md(
        "### Soal 5 - Jawaban: **d) keduanya konsisten dengan amplitudo proporsional level**",
        "",
        "Amplitudo yang membesar bersama level = ciri musiman **multiplikatif**:",
        "`y = (level + trend) x seasonal` dengan seasonal ~ rasio (1.10 berarti +10%).",
        "Alternatif setara: log dulu (`log y = log level + log seasonal`) lalu model aditif.",
        "Keduanya benar - karena log mengubah multiplikasi menjadi penjumlahan.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** aditif mengasumsikan fluktuasi konstan (±5 ribu di semua level) - bertentangan",
        "  dengan observasi.",
        "- **c)** data justru sangat bisa diforecast - polanya jelas.",
        "",
        "Di lab Bagian 7: seri sintetis kita aditif (noise konstan), jadi HW aditif lebih cocok;",
        "HW multiplikatif tetap dipakai sebagai pembanding.",
    ),
    md(
        "### Soal 6 - Jawaban: **a) error terakumulasi sepanjang horizon**",
        "",
        "Mode 1-step: setiap prediksi mengikuti satu nilai AKTUAL terbaru - error tidak menumpuk.",
        "Mode rekursif 90-step: prediksi pertama memakai data aktual, tapi prediksi kedua memakai",
        "PREDIKSI pertama sebagai input, dst. - bias & variance menumpuk sepanjang horizon.",
        "Itu sebabnya MAE 1-step = 3.0 bisa jadi MAE 90-step yang jauh lebih besar.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **b)** MAE valid di semua horizon - yang berubah adalah kesulitannya.",
        "- **c)** overfit terlihat di gap train-vs-val, bukan di gap 1-step-vs-multi-step.",
        "- **d)** ukuran val bukan penyebab akumulasi error rekursif.",
        "",
        "Di lab Bagian 8, rolling backtest menilai model di mode multi-step yang sesungguhnya -",
        "satu-satunya cara menilai model forecasting secara jujur.",
    ),
    md(
        "### Soal 7 - Jawaban: **b) lag menjadi fitur, nilai sekarang menjadi target**",
        "",
        "AR(p) = regresi linear dengan fitur berupa nilai-nilai masa lalu:",
        "baris ke-i: X[i] = [y[i-1], y[i-2], ..., y[i-p]], target y[i].",
        "Panjang data efektif menyusut: n sampel menjadi n - p baris regresi.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** itu memakai masa depan sebagai fitur - kebocoran langsung.",
        "- **c)** indeks waktu sebagai fitur = regresi tren, bukan AR.",
        "- **d)** membalik peran fitur-target: memprediksi masa lalu dari masa kini.",
        "",
        "Koneksi lab: `fit_ar_ols` (Soal 12) dan latihan AR(p) di Bagian 4 memakai",
        "konstruksi persis ini dengan `np.linalg.lstsq`.",
    ),
    md(
        "### Soal 8 - Jawaban: **b) ada trend - detrend dulu**",
        "",
        "Trend membuat y[t] dan y[t-k] sama-sama bergerak naik (atau turun) jangka panjang,",
        "sehingga korelasinya tinggi di SEMUA lag - ACF terlihat 'decaying pelan' tanpa informasi.",
        "Setelah detrend (atau differencing), ACF yang sebenarnya baru terlihat.",
        "",
        "Kenapa opsi lain salah:",
        "",
        "- **a)** white noise justru punya ACF ~0 di semua lag non-nol - kebalikan gejala.",
        "- **c)** musiman mingguan memunculkan PUNCAK berulang tiap 7 lag - tidak disebutkan.",
        "- **d)** ACF tidak butuh normalisasi - ia korelasi, invarian terhadap skala.",
        "",
        "Bukti empiris di lab Bagian 5 (sunspots): ACF mentah decay pelan (lag-1 = 0.92);",
        "setelah detrend, puncak terbesar muncul di lag 123-128 - siklus ~11 tahun.",
    ),
    md("## Bagian B - Coding (kode referensi)"),
    md(
        "### Soal 9 - `buat_window`",
        "",
        "Inti time-series ML: sliding window. Perhatikan `n = len(series) - window_size`",
        "dan bahwa target TEPAT satu langkah setelah akhir window.",
    ),
    code(
        "import numpy as np\n",
        "\n",
        "def buat_window(series, window_size):\n",
        "    series = np.asarray(series, dtype=float)\n",
        "    n = len(series) - window_size\n",
        "    X = np.empty((n, window_size))\n",
        "    for i in range(n):\n",
        "        X[i] = series[i:i + window_size]\n",
        "    y = series[window_size:]          # tepat 1 langkah ke depan\n",
        "    return X, y\n",
        "\n",
        "s = np.array([1., 2., 3., 4., 5.])\n",
        "X, y = buat_window(s, 3)\n",
        "print(X)   # [[1. 2. 3.], [2. 3. 4.]]\n",
        "print(y)   # [4. 5.]",
    ),
    md(
        "### Soal 10 - `split_waktu`",
        "",
        "Split berbasis indeks waktu - TANPA shuffle. `int(n * rasio_train)` menentukan titik potong.",
        "Edge case: `rasio_train=1.0` → val kosong tapi tetap array valid (bukan None/error).",
    ),
    code(
        "def split_waktu(X, y, rasio_train=0.8):\n",
        "    X, y = np.asarray(X), np.asarray(y)\n",
        "    cut = int(len(X) * rasio_train)\n",
        "    return X[:cut], y[:cut], X[cut:], y[cut:]\n",
        "\n",
        "X = np.arange(10.).reshape(5, 2)\n",
        "y = np.arange(5.)\n",
        "Xtr, ytr, Xva, yva = split_waktu(X, y, 0.6)\n",
        "print(Xtr.shape, Xva.shape)   # (3, 2) (2, 2)\n",
        "print(ytr, yva)               # [0. 1. 2.] [3. 4.]",
    ),
    md(
        "### Soal 11 - `metrik_semua`",
        "",
        "Tiga metrik, satu fungsi. Perhatikan: sMAPE memakai epsilon `1e-8` di pembagi agar",
        "tidak pernah membagi nol, dan hasilnya selalu terbatas [0, 2].",
        "Kesalahan umum: lupa epsilon (ZeroDivisionError saat y_true=0), atau memakai `mape`",
        "mentah yang meledak di titik nol.",
    ),
    code(
        "def metrik_semua(y_true, y_pred):\n",
        "    y_true = np.asarray(y_true, dtype=float)\n",
        "    y_pred = np.asarray(y_pred, dtype=float)\n",
        "    err = y_true - y_pred\n",
        "    mae = float(np.mean(np.abs(err)))\n",
        "    rmse = float(np.sqrt(np.mean(err ** 2)))\n",
        "    smape = float(np.mean(\n",
        "        2 * np.abs(err) / (np.abs(y_true) + np.abs(y_pred) + 1e-8)\n",
        "    ))\n",
        "    return {'mae': mae, 'rmse': rmse, 'smape': smape}\n",
        "\n",
        "m = metrik_semua(np.array([1., 3., 5., 7.]), np.array([2., 2., 4., 4.]))\n",
        "print(m)   # {'mae': 1.5, 'rmse': 1.732..., 'smape': 0.4586...}\n",
        "print(metrik_semua(np.array([0., 1.]), np.array([0., 0.]))['smape'])  # 1.0 (finite!)",
    ),
    md(
        "### Soal 12 - `fit_ar_ols`",
        "",
        "AR(p) via least-squares: bangun matriks lag lalu `lstsq`. Verifikasi empiris:",
        "series AR(1) murni dengan phi=0.5 harus menghasilkan estimasi ~0.5 (n=20000,",
        "SE kecil - toleransi 0.1 sangat longgar).",
    ),
    code(
        "def fit_ar_ols(series, p):\n",
        "    s = np.asarray(series, dtype=float)\n",
        "    # kolom k = y[t-(k+1)]: shift ke kanan sebanyak k+1\n",
        "    X = np.column_stack([s[p - k - 1:len(s) - k - 1] for k in range(p)])\n",
        "    y = s[p:]\n",
        "    return np.linalg.lstsq(X, y, rcond=None)[0]\n",
        "\n",
        "rng = np.random.default_rng(0)\n",
        "z = np.empty(20000)\n",
        "z[0] = 0.0\n",
        "e = rng.normal(0, 1, 20000)\n",
        "for i in range(1, 20000):\n",
        "    z[i] = 0.5 * z[i - 1] + e[i]\n",
        "print(fit_ar_ols(z, 1))       # ~[0.5]\n",
        "print(fit_ar_ols(np.arange(10.), 2).shape)  # (2,)",
    ),
    md(
        "---",
        "",
        "Skor penuh? Lanjut ke `project-starter-forecasting-mini/` - di sana semua konsep ini",
        "disatukan menjadi pipeline forecasting lengkap dengan mode TDD."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
