"""Generate 02_kuis_time_series.ipynb for Bab 7."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "02_kuis_time_series.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


cells = [
    md(
        "# 📝 Kuis Bab 7 - Time Series",
        "",
        "12 soal (8 pilihan ganda + 4 coding), total **23 poin**. Penilaian otomatis di cell terakhir.",
        "",
        "**Aturan:** kerjakan tanpa membuka materi. Soal coding: isi di bawah `# TODO`,",
        "lalu jalankan cell penilaian di bawah. Boleh pakai NumPy.",
    ),
    md("## Bagian A - Pilihan Ganda (isi `JAWABAN`)"),
    code(
        "# Isi jawaban pilihan ganda di sini, contoh: JAWABAN[1] = 'a'\n",
        "\n",
        "JAWABAN = {\n",
        "    1: None,\n",
        "    2: None,\n",
        "    3: None,\n",
        "    4: None,\n",
        "    5: None,\n",
        "    6: None,\n",
        "    7: None,\n",
        "    8: None,\n",
        "}",
    ),
    md(
        "### Soal 1 - Split yang benar",
        "",
        "Kamu punya 1000 titik data time series dan ingin menilai model sebelum dipakai.",
        "Cara split yang SAH:",
        "",
        "- a) `train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)`",
        "- b) acak 80% titik untuk train, 20% untuk val, tanpa shuffle eksplisit (default saja)",
        "- c) 800 titik PERTAMA untuk train, 200 titik TERAKHIR untuk val",
        "- d) 800 titik TERAKHIR untuk train, 200 titik PERTAMA untuk val",
    ),
    md(
        "### Soal 2 - Baseline mengalahkan model",
        "",
        "LSTM-mu selesai dilatih: MAE 15.8. Baseline naive (prediksi = nilai terakhir window)",
        "di data yang sama: MAE 5.1. Kesimpulan yang PALING tepat:",
        "",
        "- a) LSTM tetap lebih baik karena arsitekturnya lebih modern",
        "- b) Model gagal mengalahkan baseline → belum layak dipakai; cek data (window kecil",
        "  / noise dominan) atau sederhanakan",
        "- c) Baseline harus dihapus dari laporan karena mempermalukan model",
        "- d) MAE bukan metrik yang cocok untuk forecasting",
    ),
    md(
        "### Soal 3 - Kenapa MAPE berbahaya",
        "",
        "MAPE (`mean(|y_pred − y_true| / |y_true|)`) bisa menghasilkan angka error raksasa",
        "atau bahkan infinite. Kondisi yang memicunya:",
        "",
        "- a) `y_true` berisi nilai negatif",
        "- b) `y_true` mendekati atau sama dengan nol (pembagian meledak)",
        "- c) `y_pred` jauh lebih besar dari `y_true`",
        "- d) Terlalu banyak titik data",
    ),
    md(
        "### Soal 4 - Efek `log1p`",
        "",
        "Model dilatih pada `z = np.log1p(y)`. Prediksi model untuk z adalah 5.0.",
        "Bagaimana mengembalikan ke satuan asli?",
        "",
        "- a) `y = np.exp(5.0)`",
        "- b) `y = np.expm1(5.0)` - invers dari `log1p`",
        "- c) `y = 1 / np.exp(5.0)`",
        "- d) Tidak bisa dikembalikan (transformasi satu arah)",
    ),
    md(
        "### Soal 5 - Seasonality aditif vs multiplikatif",
        "",
        "Amplitudo fluktuasi data penjualan MEMBESAR seiring naiknya level rata-rata",
        "(fluktuasi ±2 ribu saat omzet 20 ribu, tapi ±10 ribu saat omzet 100 ribu).",
        "Model musiman yang paling tepat:",
        "",
        "- a) Aditif: `y = level + trend + seasonal`",
        "- b) Multiplikatif: `y = (level + trend) × seasonal`",
        "- c) Tidak ada model yang cocok - data harus dibuang",
        "- d) Aditif pada data yang sudah dilog-ambil, atau multiplikatif langsung -",
        "  keduanya konsisten dengan amplitudo yang proporsional terhadap level",
    ),
    md(
        "### Soal 6 - Recursive backtest penting",
        "",
        "MAE 1-step-ahead model-mu 3.0, tapi saat dipakai memprediksi 90 hari ke depan",
        "sekaligus hasilnya meleset jauh. Penjelasan paling mungkin:",
        "",
        "- a) 1-step: tiap prediksi mengikuti satu nilai AKTUAL terbaru; 90-step rekursif:",
        "  prediksi kemarin jadi input hari ini → error terakumulasi sepanjang horizon",
        "- b) MAE tidak valid untuk horizon pendek",
        "- c) Model overfit karena epochs terlalu banyak",
        "- d) Data val terlalu kecil",
    ),
    md(
        "### Soal 7 - AR(p) via OLS",
        "",
        "AR(2): `y[t] = φ₁·y[t−1] + φ₂·y[t−2]`. Kamu menyelesaikannya dengan",
        "`np.linalg.lstsq(X, y)` dengan X berisi kolom [y[t−1], y[t−2]].",
        "Baris ke-i dari X dan elemen ke-i dari y adalah…",
        "",
        "- a) X[i] = [y[i+1], y[i+2]], y[i] = y[i]",
        "- b) X[i] = [y[i−1], y[i−2]], y[i] = y[i] - lag menjadi fitur, nilai sekarang menjadi target",
        "- c) X[i] = [i, i−1], y[i] = y[i] - indeks waktu sebagai fitur",
        "- d) X[i] = [y[i], y[i−1]], y[i] = y[i−1]",
    ),
    md(
        "### Soal 8 - Membaca pola ACF",
        "",
        "ACF sebuah series: decaying pelan dari 1.0 di semua lag awal, TANPA puncak",
        "berulang pada lag tertentu. Interpretasi paling tepat:",
        "",
        "- a) White noise murni - tidak bisa diforecast",
        "- b) Ada TREND yang kuat - detrend dulu sebelum membaca pola musiman",
        "- c) Ada musiman mingguan yang kuat",
        "- d) ACF rusak karena data tidak dinormalisasi",
    ),
    md("## Bagian B - Coding"),
    md(
        "### Soal 9 - `buat_window` (3 poin)",
        "",
        "`buat_window(series, window_size)` → tuple `(X, y)`:",
        "",
        "- `X[i] = series[i : i+window_size]` (fitur: window ke belakang)",
        "- `y[i] = series[i + window_size]` (target: tepat satu langkah ke depan)",
        "- `X` bentuknya `(n, window_size)`, `y` bentuknya `(n,)`",
        "- `n = len(series) − window_size`",
    ),
    code(
        "import numpy as np\n",
        "\n",
        "def buat_window(series, window_size):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# s = np.array([1., 2., 3., 4., 5.])\n",
        "# X, y = buat_window(s, 3)\n",
        "# # X = [[1, 2, 3], [2, 3, 4]], y = [4., 5.]"
    ),
    md(
        "### Soal 10 - `split_waktu` (3 poin)",
        "",
        "`split_waktu(X, y, rasio_train=0.8)` → `(X_train, y_train, X_val, y_val)`",
        "dengan potongan PERTAMA `int(n · rasio_train)` untuk train dan sisanya val.",
        "TANPA shuffle - urutan waktu harus terjaga. `n=0` → empat array kosong yang valid.",
    ),
    code(
        "def split_waktu(X, y, rasio_train=0.8):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# X = np.arange(10.).reshape(5, 2); y = np.arange(5.)\n",
        "# Xtr, ytr, Xva, yva = split_waktu(X, y, 0.6)\n",
        "# # Xtr.shape=(3,2), Xva.shape=(2,2), ytr=[0,1,2], yva=[3,4]"
    ),
    md(
        "### Soal 11 - `metrik_semua` (5 poin)",
        "",
        "`metrik_semua(y_true, y_pred)` → dict dengan tiga kunci:",
        "",
        "- `'mae'`  : mean(|y_true − y_pred|)",
        "- `'rmse'` : sqrt(mean((y_true − y_pred)²))",
        "- `'smape'`: mean( 2·|y_t − p_t| / (|y_t| + |p_t| + 1e−8) ) - pembagi dijaga",
        "  dari nol dengan epsilon; hasil selalu dalam [0, 2]",
        "",
        "Contoh: `y_true=[1,3,5,7]`, `y_pred=[2,2,4,4]` → mae=1.5, rmse≈1.732, smape≈0.4586.",
    ),
    code(
        "def metrik_semua(y_true, y_pred):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# m = metrik_semua(np.array([1., 3., 5., 7.]), np.array([2., 2., 4., 4.]))\n",
        "# print(m)  # {'mae': 1.5, 'rmse': 1.732..., 'smape': 0.4586...}"
    ),
    md(
        "### Soal 12 - `fit_ar_ols` (4 poin)",
        "",
        "`fit_ar_ols(series, p)` → koefisien `φ (p,)` dari regresi least-squares:",
        "",
        "- Fitur: `[y[t−1], y[t−2], …, y[t−p]]` → X berukuran `(n−p, p)`",
        "- Target: `y[t]` → y berukuran `(n−p,)`",
        "- Return: `np.linalg.lstsq(X, y, rcond=None)[0]`",
        "",
        "Contoh: series AR(1) murni `y[t] = 0.5·y[t−1] + noise` (n besar) →",
        "`fit_ar_ols(series, 1)[0] ≈ 0.5` (±0.1).",
    ),
    code(
        "def fit_ar_ols(series, p):\n",
        "    # TODO\n",
        "    pass\n",
        "\n",
        "# rng = np.random.default_rng(0)\n",
        "# z = np.empty(20000); z[0] = 0.0\n",
        "# e = rng.normal(0, 1, 20000)\n",
        "# for i in range(1, 20000):\n",
        "#     z[i] = 0.5 * z[i-1] + e[i]\n",
        "# print(fit_ar_ols(z, 1))   # kira-kira [0.5]\n",
        "# print(fit_ar_ols(np.arange(10.), 2))  # tidak error, bentuk (2,)"
    ),
    md("## 🧮 Penilaian Otomatis"),
    code(
        "import numpy as np\n",
        "\n",
        "total_bobot = 23\n",
        "\n",
        "\n",
        "def jalankan_kuis():\n",
        "    skor = 0\n",
        "    rincian = []\n",
        "\n",
        "    def cek_pilihan(nomor, kunci, bobot=1):\n",
        "        nonlocal skor\n",
        "        benar = JAWABAN.get(nomor) == kunci\n",
        "        skor += bobot if benar else 0\n",
        "        rincian.append((nomor, benar))\n",
        "\n",
        "    def cek_kode(nomor, uji, bobot=1):\n",
        "        nonlocal skor\n",
        "        benar = False\n",
        "        try:\n",
        "            benar = bool(uji())\n",
        "        except Exception as e:\n",
        "            print(f'  soal {nomor}: error -> {type(e).__name__}: {e}')\n",
        "        skor += bobot if benar else 0\n",
        "        rincian.append((nomor, benar))\n",
        "\n",
        "    def approx(a, b, tol=1e-6):\n",
        "        return np.allclose(np.asarray(a, dtype=float), np.asarray(b, dtype=float), atol=tol)\n",
        "\n",
        "    def _safe(nama, *args):\n",
        "        fn = globals().get(nama)\n",
        "        if fn is None:\n",
        "            return None\n",
        "        try:\n",
        "            return fn(*args)\n",
        "        except Exception:\n",
        "            return None\n",
        "\n",
        "    cek_pilihan(1, 'c')\n",
        "    cek_pilihan(2, 'b')\n",
        "    cek_pilihan(3, 'b')\n",
        "    cek_pilihan(4, 'b')\n",
        "    cek_pilihan(5, 'd')\n",
        "    cek_pilihan(6, 'a')\n",
        "    cek_pilihan(7, 'b')\n",
        "    cek_pilihan(8, 'b')\n",
        "\n",
        "    # Soal 9 - buat_window\n",
        "    def uji9():\n",
        "        s = np.array([1., 2., 3., 4., 5.])\n",
        "        X, y = buat_window(s, 3)\n",
        "        assert X.shape == (2, 3) and y.shape == (2,)\n",
        "        assert approx(X, [[1, 2, 3], [2, 3, 4]]) and approx(y, [4, 5])\n",
        "        X2, y2 = buat_window(np.arange(10.), 7)\n",
        "        assert X2.shape == (3, 7) and approx(y2, [7, 8, 9])\n",
        "        X3, y3 = buat_window(np.array([9., 4.]), 1)\n",
        "        assert X3.shape == (1, 1) and approx(y3, [4.])\n",
        "        return True\n",
        "    cek_kode(9, uji9, bobot=3)\n",
        "\n",
        "    # Soal 10 - split_waktu\n",
        "    def uji10():\n",
        "        X = np.arange(10.).reshape(5, 2)\n",
        "        y = np.arange(5.)\n",
        "        Xtr, ytr, Xva, yva = split_waktu(X, y, 0.6)\n",
        "        assert Xtr.shape == (3, 2) and Xva.shape == (2, 2)\n",
        "        assert approx(ytr, [0, 1, 2]) and approx(yva, [3, 4])\n",
        "        assert approx(Xtr[0], [0, 1]), 'urutan waktu terjaga (tidak di-shuffle)'\n",
        "        Xtr2, ytr2, Xva2, yva2 = split_waktu(X, y, 1.0)\n",
        "        assert Xva2.shape == (0, 2) and yva2.shape == (0,)\n",
        "        return True\n",
        "    cek_kode(10, uji10, bobot=3)\n",
        "\n",
        "    # Soal 11 - metrik_semua\n",
        "    def uji11():\n",
        "        m = metrik_semua(np.array([1., 3., 5., 7.]), np.array([2., 2., 4., 4.]))\n",
        "        assert approx(m['mae'], 1.5)\n",
        "        assert approx(m['rmse'], np.sqrt((1 + 1 + 1 + 9) / 4))\n",
        "        ape = [2 * 1 / 3, 2 * 1 / 5, 2 * 1 / 9, 2 * 3 / 11]\n",
        "        assert approx(m['smape'], float(np.mean(ape)))\n",
        "        m2 = metrik_semua(np.array([0., 1.]), np.array([0., 0.]))  # ada nol!\n",
        "        assert np.isfinite(m2['smape']) and approx(m2['smape'], 1.0), 'epsilon menjaga dari nol'\n",
        "        m3 = metrik_semua(np.array([2., 2.]), np.array([2., 2.]))\n",
        "        assert m3['mae'] == 0 and m3['rmse'] == 0 and m3['smape'] == 0, 'prediksi sempurna -> nol'\n",
        "        return True\n",
        "    cek_kode(11, uji11, bobot=5)\n",
        "\n",
        "    # Soal 12 - fit_ar_ols\n",
        "    def uji12():\n",
        "        rng = np.random.default_rng(0)\n",
        "        z = np.empty(20000)\n",
        "        z[0] = 0.0\n",
        "        e = rng.normal(0, 1, 20000)\n",
        "        for i in range(1, 20000):\n",
        "            z[i] = 0.5 * z[i - 1] + e[i]\n",
        "        phi = fit_ar_ols(z, 1)\n",
        "        assert phi.shape == (1,) and abs(phi[0] - 0.5) < 0.1\n",
        "        phi2 = fit_ar_ols(np.arange(10.), 2)\n",
        "        assert phi2.shape == (2,)\n",
        "        return True\n",
        "    cek_kode(12, uji12, bobot=4)\n",
        "\n",
        "    print('=' * 46)\n",
        "    for nomor, benar in rincian:\n",
        "        print(f'  Soal {nomor:>2}: {\"BENAR\" if benar else \"salah\"}')\n",
        "    print('=' * 46)\n",
        "    print(f'SKOR AKHIR: {skor}/{total_bobot}')\n",
        "    if skor == total_bobot:\n",
        "        print('Sempurna! Lanjut ke project starter.')\n",
        "    elif skor >= 18:\n",
        "        print('Bagus! Review soal yang salah, lalu lanjut.')\n",
        "    else:\n",
        "        print('Ulangi bagian terkait di lab, coba lagi besok.')\n",
        "\n",
        "jalankan_kuis()",
    ),
    md(
        "---",
        "",
        "Sudah mencoba serius? Bandingkan pendekatanmu dengan `03_kunci_jawaban_kuis_time_series.ipynb`",
        "- fokus pada intuisi di balik tiap jawaban."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
