"""Generate 02_kuis_llm_fondasi.ipynb for Bab 9."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "02_kuis_llm_fondasi.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [l + "\n" for l in lines]}


cells = [
    md(
        "# 📝 Kuis Bab 9 — Fondasi LLM",
        "",
        "10 soal (6 pilihan ganda + 4 coding), total **22 poin**. Penilaian otomatis di cell terakhir.",
        "",
        "**Aturan:** kerjakan tanpa membuka materi. Soal coding: isi di bawah `# TODO`,",
        "lalu jalankan cell penilaian di bawah. Boleh pakai NumPy.",
    ),
    md("## Bagian A — Pilihan Ganda (isi `JAWABAN`)"),
    code(
        "# Isi jawaban pilihan ganda di sini, contoh: JAWABAN[1] = 'a'",
        "",
        "JAWABAN = {",
        "    1: None,",
        "    2: None,",
        "    3: None,",
        "    4: None,",
        "    5: None,",
        "    6: None,",
        "}",
    ),
    md(
        "### Soal 1 — Kenapa subword?",
        "",
        "Kenapa tokenizer modern (BPE/WordPiece) memecah kata langka menjadi subword,",
        "bukan memakai token `<UNK>` untuk kata yang tidak ada di vocabulary?",
        "",
        "- a) Supaya vocabulary lebih kecil sehingga model lebih cepat dilatih",
        "- b) Karena kata langka biasanya tidak penting untuk prediksi",
        "- c) Karakter/subword SELALU tersedia sebagai fallback — model bisa",
        "  men-encode teks APA PUN dan tetap menebak makna dari potongannya",
        "- d) Karena `<UNK>` membuat loss training tidak stabil",
    ),
    md(
        "### Soal 2 — Kenapa dibagi sqrt(d_k)?",
        "",
        "Pada scaled dot-product attention, skor dibagi `sqrt(d_k)`. Yang terjadi jika",
        "TIDAK dibagi:",
        "",
        "- a) Skor jadi negatif sehingga softmax tidak valid",
        "- b) Varians skor tumbuh sebesar d_k → softmax mendekati satu-hot → gradien hampir nol",
        "- c) Attention hanya bisa melihat token yang berdekatan",
        "- d) Hasilnya sama saja, pembagian itu hanya konvensi numerik",
    ),
    md(
        "### Soal 3 — Kenapa decoder butuh causal mask?",
        "",
        "Saat melatih GPT-style decoder dengan next-token prediction, causal mask wajib",
        "karena:",
        "",
        "- a) Tanpa mask, attention weights bisa bernilai negatif",
        "- b) Tanpa mask, model memakai informasi token MASA DEPAN saat memprediksi",
        "  token sekarang — loss jadi curang dan model tidak bisa generate autoregressif",
        "- c) Mask diperlukan agar jumlah parameter tidak berlebih",
        "- d) Tanpa mask, positional encoding tidak berfungsi",
    ),
    md(
        "### Soal 4 — Manakah yang murni fungsi posisi?",
        "",
        "Properti mana yang BENAR tentang positional encoding sinusoidal?",
        "",
        "- a) PE[p] bergantung pada token yang ada di posisi p",
        "- b) PE[p]·PE[q] hanya fungsi dari selisih (p−q) — karena itu relative",
        "  position bisa dibaca dari dot product",
        "- c) Nilai PE membesar tanpa batas saat posisi bertambah",
        "- d) PE dipelajari bersama parameter model, seperti embedding",
    ),
    md(
        "### Soal 5 — Efek temperature",
        "",
        "Saat memanggil LLM API, `temperature` dinaikkan dari 0.2 ke 1.5. Efeknya pada",
        "distribusi sampling:",
        "",
        "- a) Distribusi jadi lebih tajam — jawaban lebih deterministik",
        "- b) Distribusi jadi lebih datar — output lebih bervariasi/kreatif, risiko",
        "  tidak masuk akal naik",
        "- c) Tidak mengubah distribusi, hanya mengubah jumlah token output",
        "- d) Token langka otomatis dihapus dari kandidat",
    ),
    md(
        "### Soal 6 — Encoder vs decoder",
        "",
        "Kamu perlu membangun sistem klasifikasi sentimen (label: positif/negatif/netral)",
        "dengan budget kecil. Pilihan arsitektur paling tepat:",
        "",
        "- a) Decoder-only besar (GPT-style) — generate jawaban lalu parsing",
        "- b) Encoder-only (BERT-style) — bidirectional, cukup untuk memahami satu",
        "  kalimat, jauh lebih murah di-inferensi",
        "- c) Encoder-decoder (T5) — selalu paling akurat untuk semua task",
        "- d) Bukan model bahasa — pakai CNN untuk teks",
    ),
    md("## Bagian B — Coding"),
    md(
        "### Soal 7 — `softmax_stabil` (2 poin)",
        "",
        "`softmax_stabil(x, axis=-1)` → distribusi probabilitas:",
        "",
        "- Kurangi max per-baris sebelum `exp` (stabil secara numerik)",
        "- Tiap baris output berjumlah 1",
        "",
        "Contoh: `softmax_stabil([0, ln(3)])` → `[0.25, 0.75]`.",
    ),
    code(
        "import numpy as np",
        "",
        "def softmax_stabil(x, axis=-1):",
        "    # TODO",
        "    pass",
        "",
        "# p = softmax_stabil(np.array([0.0, np.log(3.0)]))",
        "# print(p)  # [0.25, 0.75]",
    ),
    md(
        "### Soal 8 — `attention` (5 poin)",
        "",
        "`attention(Q, K, V)` → tuple `(output, attn_weights)` untuk Q, K, V: `(n, d_k)`:",
        "",
        "- `scores = Q @ K.T / sqrt(d_k)`",
        "- `attn = softmax(scores)` per baris; `output = attn @ V`",
        "",
        "Contoh dengan Q=K=V (4 token, d_k=8, seed np.random.seed(9), randn):",
        "`attn.sum(axis=-1)` = semua 1; `output.shape` = `(4, 8)`.",
    ),
    code(
        "def attention(Q, K, V):",
        "    # TODO",
        "    pass",
        "",
        "# np.random.seed(9)",
        "# Q = np.random.randn(4, 8); K = np.random.randn(4, 8); V = np.random.randn(4, 8)",
        "# out, attn = attention(Q, K, V)",
        "# print(attn.sum(axis=-1).round(6))  # [1. 1. 1. 1.]",
    ),
    md(
        "### Soal 9 — `apply_causal_mask` (4 poin)",
        "",
        "`apply_causal_mask(scores)` → matrix skor yang sudah di-mask:",
        "",
        "- Posisi `(i, j)` dengan `j > i` diganti `-1e9` (segitiga atas, di atas diagonal)",
        "- Elemen lain TIDAK berubah",
        "",
        "Contoh: `apply_causal_mask([[1, 2], [3, 4]])` → `[[1, -1e9], [3, 4]]`.",
    ),
    code(
        "def apply_causal_mask(scores):",
        "    # TODO",
        "    pass",
        "",
        "# m = apply_causal_mask(np.array([[1., 2.], [3., 4.]]))",
        "# print(m)  # [[1, -1e9], [3, 4]]",
    ),
    md(
        "### Soal 10 — `sample_topk` (5 poin)",
        "",
        "`sample_topk(logits, k, rng)` → int, sampling dari k token probabilitas",
        "tertinggi:",
        "",
        "- `idx = argsort(logits)[::-1][:k]`",
        "- probabilitas dari softmax(logits[idx]) — lalu `rng.choice(idx, p=p)`",
        "",
        "Contoh: `logits=[0.1, 2.2, 0.5, 1.3, 0.1, 0.9, 0.2, 0.4]`, k=2 → hasil selalu",
        "angka 1 atau 3 (apa pun seed-nya).",
    ),
    code(
        "def sample_topk(logits, k, rng):",
        "    # TODO",
        "    pass",
        "",
        "# lg = np.array([0.1, 2.2, 0.5, 1.3, 0.1, 0.9, 0.2, 0.4])",
        "# r = np.random.default_rng(9)",
        "# print([sample_topk(lg, 2, r) for _ in range(8)])  # hanya angka 1 dan 3",
    ),
    md("## 🧮 Penilaian Otomatis"),
    code(
        "import numpy as np",
        "",
        "total_bobot = 22",
        "",
        "",
        "def jalankan_kuis():",
        "    skor = 0",
        "    rincian = []",
        "",
        "    def cek_pilihan(nomor, kunci, bobot=1):",
        "        nonlocal skor",
        "        benar = JAWABAN.get(nomor) == kunci",
        "        skor += bobot if benar else 0",
        "        rincian.append((nomor, benar))",
        "",
        "    def cek_kode(nomor, uji, bobot=1):",
        "        nonlocal skor",
        "        benar = False",
        "        try:",
        "            benar = bool(uji())",
        "        except Exception as e:",
        "            print(f'  soal {nomor}: error -> {type(e).__name__}: {e}')",
        "        skor += bobot if benar else 0",
        "        rincian.append((nomor, benar))",
        "",
        "    def approx(a, b, tol=1e-6):",
        "        return np.allclose(np.asarray(a, dtype=float), np.asarray(b, dtype=float), atol=tol)",
        "",
        "    def _safe(nama, *args):",
        "        fn = globals().get(nama)",
        "        if fn is None:",
        "            return None",
        "        try:",
        "            return fn(*args)",
        "        except Exception:",
        "            return None",
        "",
        "    cek_pilihan(1, 'c')",
        "    cek_pilihan(2, 'b')",
        "    cek_pilihan(3, 'b')",
        "    cek_pilihan(4, 'b')",
        "    cek_pilihan(5, 'b')",
        "    cek_pilihan(6, 'b')",
        "",
        "    # Soal 7 - softmax_stabil",
        "    def uji7():",
        "        p = softmax_stabil(np.array([0.0, np.log(3.0)]))",
        "        assert approx(p, [0.25, 0.75]), f'dapat {p}'",
        "        r = np.random.default_rng(0)",
        "        x = r.normal(0, 30, (5, 7))   # skala besar: versi naive akan meledak",
        "        ps = softmax_stabil(x)",
        "        assert np.allclose(ps.sum(axis=-1), 1.0), 'tiap baris jumlah 1'",
        "        assert np.all(ps >= 0) and np.all(np.isfinite(ps)), 'finite & non-negatif'",
        "        baris = ps[0]",
        "        assert np.argmax(baris) == np.argmax(x[0]), 'urutan probabilitas mengikuti skor'",
        "        return True",
        "    cek_kode(7, uji7, bobot=2)",
        "",
        "    # Soal 8 - attention",
        "    def uji8():",
        "        np.random.seed(9)",
        "        Q = np.random.randn(4, 8); K = np.random.randn(4, 8); V = np.random.randn(4, 8)",
        "        out, attn = attention(Q, K, V)",
        "        assert out.shape == (4, 8) and attn.shape == (4, 4)",
        "        assert np.allclose(attn.sum(axis=-1), 1.0, atol=1e-9), 'baris softmax jumlah 1'",
        "        assert np.all(attn > 0), 'softmax positif'",
        "        assert np.allclose(out, attn @ V), 'output = attn @ V'",
        "        # skor wajib diskalakan",
        "        e = np.exp(Q @ K.T)",
        "        attn_noscale = e / e.sum(axis=-1, keepdims=True)",
        "        assert not np.allclose(attn, attn_noscale), 'harus dibagi sqrt(d_k)'",
        "        return True",
        "    cek_kode(8, uji8, bobot=5)",
        "",
        "    # Soal 9 - apply_causal_mask",
        "    def uji9():",
        "        m = apply_causal_mask(np.array([[1., 2.], [3., 4.]]))",
        "        assert approx(m, [[1, -1e9], [3, 4]]), f'dapat {m}'",
        "        s = np.random.default_rng(3).normal(0, 1, (5, 5))",
        "        mm = apply_causal_mask(s.copy())",
        "        mask = np.triu(np.ones((5, 5)), k=1) == 1",
        "        assert np.allclose(mm[mask], -1e9, atol=100), 'posisi masa depan jadi -1e9'",
        "        assert np.allclose(mm[~mask], s[~mask]), 'elemen lain tetap'",
        "        return True",
        "    cek_kode(9, uji9, bobot=4)",
        "",
        "    # Soal 10 - sample_topk",
        "    def uji10():",
        "        lg = np.array([0.1, 2.2, 0.5, 1.3, 0.1, 0.9, 0.2, 0.4])",
        "        r = np.random.default_rng(9)",
        "        for _ in range(50):",
        "            assert sample_topk(lg, 2, r) in (1, 3), 'top-2 hanya dari {1, 3}'",
        "        r2 = np.random.default_rng(0)",
        "        hasil3 = {sample_topk(lg, 3, r2) for _ in range(300)}",
        "        assert hasil3 <= {1, 3, 5}, f'top-3 = {sorted(hasil3)} — harus subset {{1,3,5}}'",
        "        return True",
        "    cek_kode(10, uji10, bobot=5)",
        "",
        "    print('=' * 46)",
        "    for nomor, benar in rincian:",
        "        print(f'  Soal {nomor:>2}: {\"BENAR\" if benar else \"salah\"}')",
        "    print('=' * 46)",
        "    print(f'SKOR AKHIR: {skor}/{total_bobot}')",
        "    if skor == total_bobot:",
        "        print('Sempurna! Lanjut ke project starter.')",
        "    elif skor >= 17:",
        "        print('Bagus! Review soal yang salah, lalu lanjut.')",
        "    else:",
        "        print('Ulangi bagian terkait di lab, coba lagi besok.')",
        "",
        "jalankan_kuis()",
    ),
    md(
        "---",
        "",
        "Sudah mencoba serius? Bandingkan pendekatanmu dengan `03_kunci_jawaban_kuis_llm_fondasi.ipynb`",
        "— fokus pada intuisi di balik tiap jawaban.",
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("wrote", OUT, f"({len(cells)} cells)")
