"""Generate starter.ipynb & solusi.ipynb for the Ch5 CNN-mini project."""
import json
from pathlib import Path

BASE = Path("AI-Engineering-Curriculum/05-Computer-Vision/project-starter-cnn-mini")


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [*lines, ""]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": [*lines, ""]}


def nb(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def tulis(nama, cells):
    path = BASE / nama
    path.write_text(json.dumps(nb(cells), indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", path)


SETUP = [
    "import sys\n",
    "from pathlib import Path\n",
    "\n",
    "sys.path.insert(0, str(Path.cwd()))\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "from nn_mini.data import NILAI_KELAS, muat_semua\n",
    "from nn_mini.train import train_model\n",
    "\n",
    "X_train, y_train, X_val, y_val, X_test, y_test = muat_semua()\n",
    "print('splits:', len(y_train), len(y_val), len(y_test),\n",
    "      '| vertikal:', int(y_train.sum()), int(y_val.sum()), int(y_test.sum()))\n",
]

# ============================== STARTER ==============================
starter = [
    md(
        "# 🏗️ Starter — CNN Mini dari Nol (Bab 5)",
        "",
        "> Notebook eksperimen. **Prasyarat:** semua 42 test hijau",
        "> (`python -m unittest discover -s tests -v`).",
        "",
        "**Aturan main:** semua keputusan (filter, augmentasi, lr, early stop) diambil di",
        "**validation set**. Test set hanya disentuh di Bagian 7, sekali.",
    ),
    md("## Setup & Peta Data"),
    code(*SETUP),
    code(
        "# Lihat dulu bentuk datanya — gambar 8x8, satu garis terang horizontal/vertikal\n",
        "fig, axes = plt.subplots(2, 6, figsize=(12, 4.5))\n",
        "for k, kelas in enumerate([0, 1]):\n",
        "    contoh = X_train[y_train == kelas][:6]\n",
        "    for j in range(6):\n",
        "        axes[k, j].imshow(contoh[j], cmap='gray')\n",
        "        axes[k, j].set_title(NILAI_KELAS[kelas], fontsize=9)\n",
        "        axes[k, j].axis('off')\n",
        "plt.suptitle('Dataset \"bars\": 0 = horizontal, 1 = vertikal')\n",
        "plt.tight_layout(); plt.show()\n",
    ),
    md(
        "## Bagian 1 — Baseline MLP di Piksel Mentah Dulu",
        "",
        "Sebelum CNN, buktikan bahwa MLP yang mengahmali posisi piksel itu rapuh.",
        "Pakai `Dense` dari `nn_mini.nnet` (sudah diberikan) — flatten manual + MLP 64-16-1.",
    ),
    code(
        "from nn_mini.nnet import Dense, Sequential\n",
        "\n",
        "Xtr = X_train.reshape(len(X_train), -1)\n",
        "Xva = X_val.reshape(len(X_val), -1)\n",
        "\n",
        "mlp = Sequential([Dense(64, activation='relu', seed=1),\n",
        "                  Dense(16, activation='relu', seed=2),\n",
        "                  Dense(1, activation='sigmoid', seed=3)])\n",
        "hist_mlp = train_model(mlp, Xtr, y_train, Xva, y_val,\n",
        "                       epochs=60, batch_size=32, lr=0.3, seed=0)\n",
        "print(f'MLP (piksel mentah): val acc = {hist_mlp[\"val_acc\"][-1]:.4f}')\n",
        "print('-> Catat angka ini. CNN nanti HARUS mengalahkannya.')\n",
    ),
    md(
        "**Refleksi 1:** MLP boleh saja mencapai akurasi tinggi di val — tapi data ini",
        "punya garis di POSISI ACAK. Lihat eksperimen Bagian 6: apa yang terjadi kalau",
        "garis-geser muncul di data yang tidak pernah dilihat model?",
    ),
    md("## Bagian 2 — CNN Pertamamu"),
    code(
        "from nn_mini.model import CNNMini\n",
        "\n",
        "cnn = CNNMini(seed=0)\n",
        "hist_cnn = train_model(cnn, X_train, y_train, X_val, y_val,\n",
        "                       epochs=30, batch_size=32, lr=0.5, seed=0)\n",
        "print(f'CNN mini: val acc = {hist_cnn[\"val_acc\"][-1]:.4f}')\n",
        "\n",
        "plt.figure(figsize=(11, 4))\n",
        "plt.subplot(1, 2, 1)\n",
        "plt.plot(hist_mlp['train_loss'], label='MLP train')\n",
        "plt.plot(hist_mlp['val_loss'], '--', label='MLP val')\n",
        "plt.plot(hist_cnn['train_loss'], label='CNN train')\n",
        "plt.plot(hist_cnn['val_loss'], '--', label='CNN val')\n",
        "plt.xlabel('epoch'); plt.ylabel('BCE'); plt.title('Loss'); plt.legend()\n",
        "plt.subplot(1, 2, 2)\n",
        "plt.plot(hist_mlp['val_acc'], label='MLP')\n",
        "plt.plot(hist_cnn['val_acc'], label='CNN')\n",
        "plt.xlabel('epoch'); plt.ylabel('val accuracy'); plt.title('Akurasi'); plt.legend()\n",
        "plt.tight_layout(); plt.show()\n",
    ),
    md(
        "**Refleksi 2:** CNN mencapai akurasi tinggi dengan LEBIH SEDIKIT parameter",
        "(9 bobot filter + 17 dense vs ±1.300 MLP). Kenapa weight sharing begitu efektif",
        "untuk pola yang posisinya tidak tetap?",
    ),
    md("## Bagian 3 — Membedah Model: Apa yang Dipelajari Filter?"),
    code(
        "# Visualisasikan filter yang sudah DILATIH + responsnya terhadap dua kelas\n",
        "K = cnn.conv.K\n",
        "print('Filter 3x3 hasil training:\\n', np.round(K, 2))\n",
        "\n",
        "from nn_mini.conv import pad_zero, conv2d_forward, maxpool2x2_forward\n",
        "\n",
        "fig, axes = plt.subplots(2, 4, figsize=(13, 6))\n",
        "for k, kelas in enumerate([0, 1]):\n",
        "    img = X_val[y_val == kelas][0]\n",
        "    resp = conv2d_forward(pad_zero(img[None], 1), K)[0]\n",
        "    axes[k, 0].imshow(img, cmap='gray'); axes[k, 0].set_title('input')\n",
        "    axes[k, 1].imshow(resp, cmap='viridis'); axes[k, 1].set_title('setelah conv')\n",
        "    axes[k, 2].imshow(np.maximum(resp, 0), cmap='viridis'); axes[k, 2].set_title('setelah ReLU')\n",
        "    axes[k, 3].imshow(maxpool2x2_forward(np.maximum(resp, 0)[None])[0], cmap='viridis')\n",
        "    axes[k, 3].set_title('setelah max-pool')\n",
        "    for j in range(4):\n",
        "        axes[k, j].axis('off')\n",
        "plt.suptitle('Aliran informasi: conv → ReLU → pool')\n",
        "plt.tight_layout(); plt.show()\n",
    ),
    md(
        "**Refleksi 3:** bandingkan peta aktivasi kedua kelas. Di mana perbedaannya paling",
        "besar? Nilai tunggal mana yang akhirnya 'membaca' dense layer? (hint: nilai MAKSIMUM)",
    ),
    md("## Bagian 4 — Eksperimen Ukuran Filter (satu variabel per percobaan)"),
    code(
        "# TODO: jalankan CNNMini dengan kernel lain: 1x1, 2x2, 5x5 (pad disesuaikan\n",
        "# supaya output tetap 4x4 setelah pool: pad = (k-1)//2).\n",
        "# Catat val acc — apakah lebih besar selalu lebih baik?\n",
        "\n",
        "# for kh in [1, 2, 3, 5]:\n",
        "#     m = CNNMini(kh=kh, kw=kh, pad=(kh - 1) // 2, seed=0)\n",
        "#     h = train_model(m, X_train, y_train, X_val, y_val,\n",
        "#                     epochs=30, batch_size=32, lr=0.5, seed=0)\n",
        "#     print(f'kernel {kh}x{kh}: val acc = {h[\"val_acc\"][-1]:.4f}')\n",
    ),
    md(
        "**Refleksi 4:** kernel 1x1 tidak bisa melihat tetangga — kenapa dia tetap bisa",
        "belajar (atau gagal)? Kapan filter besar justru merugikan? (ingat: berapa parameter,\n",
        "berapa banyak piksel tepi yang hilang tanpa padding)",
    ),
    md("## Bagian 5 — Augmentasi: Flip, Noise, Shift"),
    code(
        "from nn_mini.augment import augment_batch, random_shift\n",
        "\n",
        "# TODO: bandingkan training TANPA vs DENGAN augmentasi tiap epoch.\n",
        "# Pipeline: tiap epoch sebelum training, augment salinan batch data.\n",
        "# Perhatikan: augmentasi HANYA di training — val/test tetap apa adanya!\n",
        "\n",
        "# rng = np.random.default_rng(0)\n",
        "# X_aug, y_aug = augment_batch(X_train, y_train, rng, p_noise=0.15)\n",
        "# cnn_aug = CNNMini(seed=0)\n",
        "# hist_aug = train_model(cnn_aug, X_aug, y_aug, X_val, y_val,\n",
        "#                        epochs=30, batch_size=32, lr=0.5, seed=0)\n",
        "# print(f'CNN + augmentasi: val acc = {hist_aug[\"val_acc\"][-1]:.4f}')\n",
    ),
    md(
        "**Refleksi 5:** augmentasi mana yang membantu di dataset ini, mana yang tidak?",
        "Ingat aturan Bab 5: augmentasi harus masuk akal untuk domain. Kenapa flip",
        "horizontal aman untuk garis, tapi mengubah 'horizontal' jadi 'vertikal' justru\n",
        "MERUSAK label? (jangan lakukan flip vertikal di dataset ini!)",
    ),
    md("## Bagian 6 — Ujian Sesungguhnya: Garis di Posisi Baru"),
    code(
        "# TODO: uji ketahanan — geser SEMUA gambar val beberapa piksel, bandingkan MLP vs CNN.\n",
        "# Model yang belajar 'bentuk' (CNN) harus jauh lebih tahan daripada yang\n",
        "# mengahmali 'posisi' (MLP).\n",
        "\n",
        "# from nn_mini.augment import random_shift\n",
        "# rng = np.random.default_rng(7)\n",
        "# for geser in [1, 2, 3]:\n",
        "#     Xv = random_shift(X_val, rng, max_shift=geser)\n",
        "#     acc_mlp = float(((mlp.predict_proba(Xv.reshape(len(Xv), -1)) >= 0.5) == y_val).mean())\n",
        "#     acc_cnn = float(((cnn.predict_proba(Xv) >= 0.5) == y_val).mean())\n",
        "#     print(f'geser ±{geser}px: MLP = {acc_mlp:.3f} | CNN = {acc_cnn:.3f}')\n",
    ),
    md("## Bagian 7 — Test Set (SEKALI, di akhir)"),
    code(
        "# TODO: pilih model TERBAIKMU berdasarkan val, baru sentuh test set:\n",
        "# p_test = cnn.predict_proba(X_test)\n",
        "# acc_test = float(((p_test >= 0.5) == y_test).mean())\n",
        "# print(f'TEST accuracy: {acc_test:.4f}')\n",
        "#\n",
        "# Lihat 5 prediksi pertama:\n",
        "# for i in range(5):\n",
        "#     pred = int(p_test[i] >= 0.5)\n",
        "#     print(f'sampel {i}: prediksi={NILAI_KELAS[pred]}, benar={NILAI_KELAS[y_test[i]]}, '\n",
        "#           f'p={p_test[i]:.2f}', '✓' if pred == y_test[i] else '✗')\n",
    ),
    md(
        "---",
        "",
        "Selesai? Isi `RUBRIK.md` dengan jujur, baru bandingkan dengan `solusi.ipynb`",
        "dan `solusi/cnn_mini_ref.py`.",
    ),
]

# ============================== SOLUSI ==============================
solusi = [
    md(
        "# 🔑 Solusi — CNN Mini dari Nol (Bab 5)",
        "",
        "> **Buka HANYA SETELAH** mengerjakan `starter.ipynb` + semua test hijau.",
        "Cell di notebook ini memakai implementasi referensi (`solusi/cnn_mini_ref.py`)",
        "supaya bisa dijalankan meskipun stub `nn_mini` kamu masih TODO — angkanya",
        "jadi pembanding untuk eksperimenmu.",
    ),
    md("## Setup"),
    code(
        "import sys\n",
        "from pathlib import Path\n",
        "\n",
        "sys.path.insert(0, str(Path.cwd()))\n",
        "sys.path.insert(0, str(Path.cwd() / 'solusi'))\n",
        "\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "\n",
        "import cnn_mini_ref as ref\n",
        "from nn_mini.data import NILAI_KELAS, muat_semua\n",
        "from nn_mini.nnet import Dense, Sequential\n",
        "from nn_mini.train import train_model\n",
        "\n",
        "X_train, y_train, X_val, y_val, X_test, y_test = muat_semua()\n",
        "print('splits:', len(y_train), len(y_val), len(y_test))\n",
    ),
    md("## Baseline MLP (piksel mentah)"),
    code(
        "Xtr = X_train.reshape(len(X_train), -1)\n",
        "Xva = X_val.reshape(len(X_val), -1)\n",
        "\n",
        "mlp = Sequential([Dense(64, activation='relu', seed=1),\n",
        "                  Dense(16, activation='relu', seed=2),\n",
        "                  Dense(1, activation='sigmoid', seed=3)])\n",
        "hist_mlp = train_model(mlp, Xtr, y_train, Xva, y_val,\n",
        "                       epochs=60, batch_size=32, lr=0.3, seed=0)\n",
        "print(f'MLP: val acc = {hist_mlp[\"val_acc\"][-1]:.4f}')\n",
    ),
    md("## CNN Mini (implementasi referensi)"),
    code(
        "cnn = ref.CNNMini(seed=0)\n",
        "hist_cnn = train_model(cnn, X_train, y_train, X_val, y_val,\n",
        "                       epochs=30, batch_size=32, lr=0.5, seed=0)\n",
        "print(f'CNN: val acc = {hist_cnn[\"val_acc\"][-1]:.4f}, '\n",
        "      f'val loss = {hist_cnn[\"val_loss\"][-1]:.4f}')\n",
        "\n",
        "plt.figure(figsize=(11, 4))\n",
        "plt.subplot(1, 2, 1)\n",
        "plt.plot(hist_mlp['train_loss'], label='MLP train')\n",
        "plt.plot(hist_mlp['val_loss'], '--', label='MLP val')\n",
        "plt.plot(hist_cnn['train_loss'], label='CNN train')\n",
        "plt.plot(hist_cnn['val_loss'], '--', label='CNN val')\n",
        "plt.xlabel('epoch'); plt.ylabel('BCE'); plt.title('Loss'); plt.legend()\n",
        "plt.subplot(1, 2, 2)\n",
        "plt.plot(hist_mlp['val_acc'], label='MLP')\n",
        "plt.plot(hist_cnn['val_acc'], label='CNN')\n",
        "plt.xlabel('epoch'); plt.ylabel('val accuracy'); plt.title('Akurasi'); plt.legend()\n",
        "plt.tight_layout(); plt.show()\n",
    ),
    md("## Filter yang dipelajari"),
    code(
        "K = cnn.conv.K\n",
        "print('Filter 3x3 hasil training:\\n', np.round(K, 2))\n",
        "\n",
        "from nn_mini.conv import conv2d_forward, maxpool2x2_forward, pad_zero\n",
        "\n",
        "fig, axes = plt.subplots(2, 4, figsize=(13, 6))\n",
        "for k, kelas in enumerate([0, 1]):\n",
        "    img = X_val[y_val == kelas][0]\n",
        "    resp = conv2d_forward(pad_zero(img[None], 1), K)[0]\n",
        "    axes[k, 0].imshow(img, cmap='gray'); axes[k, 0].set_title('input')\n",
        "    axes[k, 1].imshow(resp, cmap='viridis'); axes[k, 1].set_title('setelah conv')\n",
        "    axes[k, 2].imshow(np.maximum(resp, 0), cmap='viridis'); axes[k, 2].set_title('setelah ReLU')\n",
        "    axes[k, 3].imshow(maxpool2x2_forward(np.maximum(resp, 0)[None])[0], cmap='viridis')\n",
        "    axes[k, 3].set_title('setelah max-pool')\n",
        "    for j in range(4):\n",
        "        axes[k, j].axis('off')\n",
        "plt.suptitle('Aliran informasi: conv → ReLU → pool')\n",
        "plt.tight_layout(); plt.show()\n",
    ),
    md("## Eksperimen ukuran kernel"),
    code(
        "for kh in [1, 2, 3, 5]:\n",
        "    m = ref.CNNMini(kh=kh, kw=kh, pad=(kh - 1) // 2, seed=0)\n",
        "    h = train_model(m, X_train, y_train, X_val, y_val,\n",
        "                    epochs=30, batch_size=32, lr=0.5, seed=0)\n",
        "    print(f'kernel {kh}x{kh}: val acc = {h[\"val_acc\"][-1]:.4f}')\n",
    ),
    md(
        "Kernel 3x3 cukup: garis hanya butuh deteksi 'baris terang' lokal + pooling.",
        "Kernel 1x1 tetap bisa belajar (kontras garis vs latar cukup informatif),",
        "tapi kehilangan konteks tetangga; kernel besar menambah parameter tanpa",
        "tambahan informasi yang berguna di gambar 8x8.",
    ),
    md("## Ketahanan terhadap pergeseran: MLP vs CNN"),
    code(
        "from nn_mini.augment import random_shift\n",
        "\n",
        "rng = np.random.default_rng(7)\n",
        "for geser in [1, 2, 3]:\n",
        "    Xv = random_shift(X_val, rng, max_shift=geser)\n",
        "    acc_mlp = float(((mlp.predict_proba(Xv.reshape(len(Xv), -1)) >= 0.5) == y_val).mean())\n",
        "    acc_cnn = float(((cnn.predict_proba(Xv) >= 0.5) == y_val).mean())\n",
        "    print(f'geser ±{geser}px: MLP = {acc_mlp:.3f} | CNN = {acc_cnn:.3f}')\n",
    ),
    md(
        "CNN jauh lebih tahan: konvolusi + pooling mencari POLA, bukan POSISI.",
        "MLP yang mengahmali koordinat piksel kehilangan akurasi begitu garis pindah.",
    ),
    md("## Test set (sekali, di akhir)"),
    code(
        "p_test = cnn.predict_proba(X_test)\n",
        "acc_test = float(((p_test >= 0.5) == y_test).mean())\n",
        "print(f'TEST accuracy: {acc_test:.4f}')\n",
        "\n",
        "for i in range(5):\n",
        "    pred = int(p_test[i] >= 0.5)\n",
        "    print(f'sampel {i}: prediksi={NILAI_KELAS[pred]}, benar={NILAI_KELAS[y_test[i]]}, '\n",
        "          f'p={p_test[i]:.2f}', '✓' if pred == y_test[i] else '✗')\n",
    ),
]

tulis("starter.ipynb", starter)
tulis("solusi.ipynb", solusi)
